#!/usr/bin/env python3
"""
PRAYCG Offline Interpretation Reporter v1.5.5

Deterministic report generator for PRAYCG Master Comprehensive Suite output folders.
It reads CSV/JSON outputs, applies cautious rule-based summaries, and writes a
plain-language Markdown/TXT/JSON report for offline review.

This is NOT an AI model. It does not discover truth, infer private experience, or
certify endpoints. It translates existing module outputs into a bounded readable report.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import numpy as np
import pandas as pd

VERSION = "1.5.5"


def fnum(x: Any, nd: int = 3, default: str = "n/a") -> str:
    try:
        if x is None or pd.isna(x):
            return default
        return f"{float(x):.{nd}f}"
    except Exception:
        return default


def as_float(x: Any, default: float = np.nan) -> float:
    try:
        if x is None:
            return default
        if isinstance(x, str) and not x.strip():
            return default
        return float(x)
    except Exception:
        return default


def as_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    if isinstance(x, (int, float)) and not pd.isna(x):
        return bool(x)
    if isinstance(x, str):
        return x.strip().lower() in {"true", "1", "yes", "pass", "passed"}
    return False


def find_file(root: Path, patterns: Iterable[str]) -> Optional[Path]:
    roots = [root, root / "tables", root / "report", root / "reports"]
    hits: List[Path] = []
    for r in roots:
        if not r.exists():
            continue
        for pat in patterns:
            hits.extend(r.glob(pat))
    hits = [h for h in hits if h.is_file() and "template" not in h.name.lower()]
    if not hits:
        return None
    hits.sort(key=lambda p: (len(p.name), str(p)))
    return hits[0]


def read_csv(path: Optional[Path]) -> pd.DataFrame:
    if not path:
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


def read_json(path: Optional[Path]) -> Any:
    if not path:
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def table_status(df: pd.DataFrame) -> str:
    return "available" if not df.empty else "not available"


class ReportBuilder:
    def __init__(self, analysis_folder: Path):
        self.root = analysis_folder.resolve()
        if self.root.name.lower() == "tables":
            self.root = self.root.parent
        self.tables = self.root / "tables"
        self.paths: Dict[str, Optional[Path]] = {}
        self.data: Dict[str, Any] = {}

    def load(self) -> None:
        specs = {
            "module_registry": ["*module*registry*.csv"],
            "tier_map": ["*tier*map*.csv", "*boxed*recommended*.csv"],
            "phase_coverage": ["*phase*coverage*.csv"],
            "stream_inventory": ["*stream*inventory*.csv"],
            "als_qc": ["*als*start*pulse*.csv", "*ALS*QC*.csv"],
            "amred_summary": ["*amred*primary*endpoint*summary*.csv"],
            "amred_table": ["*amred*anchor*endpoint*.csv"],
            "mred_peak_summary": ["*mred_peak_resolution*run*summary*.csv"],
            "mred_peak_table": ["*mred_peak_resolution*anchor*.csv"],
            "candidate_kht": ["*candidate*local*kht*topo*mred*event*.csv", "*candidate_local*kht*.csv"],
            "mred_event": ["*mred*event_table*.csv"],
            "nip": ["*nip*component*timeseries*.csv"],
            "cii": ["*cii*anchor*integrals*.csv"],
            "tti": ["*tti*global*summary*.csv"],
            "nupi": ["*nupi*run*summary*.csv"],
            "cet": ["*cet*residualization*model*summary*.csv"],
            "eet": ["*eet*endogenous*echo*.csv"],
            "mred_itp": ["*mred_itp*anchor*summary*.csv"],
            "ocm_rsm": ["*ocm*rsm*cvb*squint*cue*.csv", "*ocm025*rsm*.csv"],
            "rsm_corr": ["*rsm*correlation*summary*.csv"],
            "nast": ["*nast*phase*transition*.csv"],
            "baseline2": ["*baseline1*baseline2*summary*.csv", "*baseline*2*summary*.csv"],
            "gammascalpel": ["*gammascalpel*microband*.csv"],
            "self_final_json": ["*final_master_report*.json"],
            "interpretation_json": ["*interpretation*.json"],
        }
        for key, pats in specs.items():
            p = find_file(self.root, pats)
            self.paths[key] = p
            self.data[key] = read_json(p) if key.endswith("json") else read_csv(p)

    def lines(self) -> List[str]:
        self.load()
        L: List[str] = []
        L.append(f"# PRAYCG Offline Interpretation Report\n")
        L.append(f"Generated by deterministic PRAYCG Offline Interpretation Reporter v{VERSION}.\n")
        L.append(f"\n**Analysis folder:** `{self.root}`\n")
        L.append("\n> Boundary: this report is a rule-based summary of existing module outputs. It does not certify meaning, consciousness, memory formation, OSM biology, or private experience. Use it as a review aid, not as a final scientific conclusion.\n")
        self._overview(L)
        self._qc(L)
        self._boxed_path(L)
        self._amred(L)
        self._mred_peak_resolution(L)
        self._mred_kht(L)
        self._nip_tti_nupi(L)
        self._cet_eet_itp(L)
        self._override_modules(L)
        self._baseline_selfreport(L)
        self._missing_modules(L)
        self._final(L)
        return L

    def _overview(self, L: List[str]) -> None:
        L.append("\n## 1. Run-level orientation\n")
        reg = self.data.get("module_registry", pd.DataFrame())
        if isinstance(reg, pd.DataFrame) and not reg.empty:
            L.append(f"Module registry detected with **{len(reg)}** rows. This usually means the folder is a consolidated Master Suite output.\n")
        else:
            L.append("No module registry table was found. The reporter will summarize whatever tables it can find.\n")
        tier = self.data.get("tier_map", pd.DataFrame())
        if isinstance(tier, pd.DataFrame) and not tier.empty:
            L.append("A module-tier map was found. The report uses the current recommended compression: QC → A-MRED primary path, with NIP/TTI/NUPI secondary and the rest exploratory/convergence.\n")

    def _qc(self, L: List[str]) -> None:
        L.append("\n## 2. QC and timing gates\n")
        als = self.data.get("als_qc", pd.DataFrame())
        if isinstance(als, pd.DataFrame) and not als.empty:
            pass_cols = [c for c in als.columns if "pass" in c.lower() or "detected" in c.lower() or "result" in c.lower() or "status" in c.lower()]
            L.append(f"ALS/timing QC table found with **{len(als)}** rows. ")
            if pass_cols:
                vals = []
                for c in pass_cols:
                    vc = als[c].astype(str).str.lower().value_counts().to_dict()
                    vals.append(f"`{c}`={vc}")
                L.append("Detected status columns: " + "; ".join(vals[:4]) + ".\n")
            else:
                L.append("No obvious pass/fail column was detected; inspect the table directly.\n")
        else:
            L.append("No ALS/start-pulse QC table was found. Treat timing-sensitive endpoint claims cautiously.\n")
        phase = self.data.get("phase_coverage", pd.DataFrame())
        if isinstance(phase, pd.DataFrame) and not phase.empty:
            L.append(f"Phase coverage table found with **{len(phase)}** rows. This supports checking whether all protocol periods have usable samples.\n")
        stream = self.data.get("stream_inventory", pd.DataFrame())
        if isinstance(stream, pd.DataFrame) and not stream.empty:
            L.append(f"Stream inventory found with **{len(stream)}** rows. Use this to verify which LSL streams were actually recorded.\n")

    def _boxed_path(self, L: List[str]) -> None:
        L.append("\n## 3. Boxed recommended interpretation path\n")
        L.append("```text\nPRIMARY PATH:\n  Timing/QC + StimulusFingerprint/CET-R + artifact/confound gates -> A-MRED\n\nSECONDARY:\n  NIP/BIT/CII/IAQ, TTI, NUPI, MRED-Peak/Resolution\n\nEXPLORATORY / CONVERGENCE:\n  KHT-topo, NAST, EET, MRED-ITP/ACG/OCU, OCM025/RSM/CVB/SquintProxy, LSO when applicable\n```\n")

    def _amred(self, L: List[str]) -> None:
        L.append("\n## 4. A-MRED primary endpoint\n")
        summ = self.data.get("amred_summary", pd.DataFrame())
        tab = self.data.get("amred_table", pd.DataFrame())
        if isinstance(summ, pd.DataFrame) and not summ.empty:
            r = summ.iloc[0]
            L.append("A-MRED summary found. ")
            for c in ["A_MRED_passes", "amred_passes", "strict_passes", "anchors_evaluated", "total_anchors", "claim_grade", "overall_interpretation"]:
                if c in summ.columns:
                    L.append(f"`{c}`={r.get(c)}. ")
            L.append("\n")
        elif isinstance(tab, pd.DataFrame) and not tab.empty:
            pass_cols = [c for c in tab.columns if c.lower() in {"a_mred_pass", "amred_pass", "strict_pass"}]
            n = len(tab)
            if pass_cols:
                passes = int(tab[pass_cols[0]].apply(as_bool).sum())
                L.append(f"A-MRED anchor table found: **{passes}/{n}** anchors passed `{pass_cols[0]}`.\n")
            else:
                L.append(f"A-MRED anchor table found with **{n}** rows, but no obvious strict-pass column.\n")
        else:
            L.append("No A-MRED table found. The primary endpoint cannot be summarized.\n")

    def _mred_peak_resolution(self, L: List[str]) -> None:
        L.append("\n## 5. MRED-Peak vs MRED-Resolution endpoint compression\n")
        summ = self.data.get("mred_peak_summary", pd.DataFrame())
        tab = self.data.get("mred_peak_table", pd.DataFrame())
        if isinstance(summ, pd.DataFrame) and not summ.empty:
            r = summ.iloc[0]
            anchors_eval = r.get('anchors_evaluated', r.get('anchor_count', 'n/a'))
            strict_peak = r.get('strict_peak_passes', r.get('strict_peak_pass_count', 'n/a'))
            res_cand = r.get('resolution_candidates', r.get('resolution_candidate_count', 'n/a'))
            L.append(f"MRED-Peak/Resolution summary found: anchors evaluated = **{anchors_eval}**, strict peak passes = **{strict_peak}**, resolution candidates = **{res_cand}**.\n")
            L.append(f"Top peak: `{r.get('top_peak_anchor_id','n/a')}` ({fnum(r.get('top_peak_score'))}, {r.get('top_peak_gate','n/a')}). Top resolution: `{r.get('top_resolution_anchor_id','n/a')}` ({fnum(r.get('top_resolution_score'))}, {r.get('top_resolution_gate','n/a')}).\n")
            L.append(f"Overall interpretation: **{r.get('overall_interpretation','n/a')}**.\n")
        elif isinstance(tab, pd.DataFrame) and not tab.empty:
            L.append(f"MRED-Peak/Resolution anchor table found with **{len(tab)}** rows. Run the v1.5.5 summary module to generate the run-level summary.\n")
        else:
            L.append("No MRED-Peak/Resolution table found. Run `praycg_mred_peak_resolution_module_v1_5_5.py` on this folder.\n")

    def _mred_kht(self, L: List[str]) -> None:
        L.append("\n## 6. MRED / CandidateLocal KHT-topo\n")
        cand = self.data.get("candidate_kht", pd.DataFrame())
        if isinstance(cand, pd.DataFrame) and not cand.empty:
            L.append(f"CandidateLocal/KHT-style table found with **{len(cand)}** rows. ")
            for col in ["A_MRED_pass", "final_lock", "event_lock", "strict_lock"]:
                if col in cand.columns:
                    L.append(f"`{col}` passes: **{int(cand[col].apply(as_bool).sum())}**. ")
            k_cols = [c for c in cand.columns if "kht" in c.lower() or c.lower() in {"k_local", "local_k"}]
            if k_cols:
                c = k_cols[0]
                L.append(f"Max `{c}`: **{fnum(pd.to_numeric(cand[c], errors='coerce').max())}**. ")
            L.append("\n")
        else:
            L.append("No CandidateLocal/KHT table found.\n")
        mred = self.data.get("mred_event", pd.DataFrame())
        if isinstance(mred, pd.DataFrame) and not mred.empty:
            quad_cols = [c for c in mred.columns if "quadrant" in c.lower() or "mred" in c.lower()]
            if quad_cols:
                vc = mred[quad_cols[0]].astype(str).value_counts().head(8).to_dict()
                L.append(f"MRED event table found. Top state labels from `{quad_cols[0]}`: `{vc}`.\n")
            else:
                L.append(f"MRED event table found with **{len(mred)}** rows.\n")

    def _nip_tti_nupi(self, L: List[str]) -> None:
        L.append("\n## 7. NIP/CII, TTI, and NUPI\n")
        cii = self.data.get("cii", pd.DataFrame())
        if isinstance(cii, pd.DataFrame) and not cii.empty and {"condition", "CII"}.issubset(cii.columns):
            tmp = cii.copy()
            tmp["condition_norm"] = tmp["condition"].astype(str).str.upper()
            means = tmp.groupby("condition_norm")["CII"].mean(numeric_only=True).to_dict()
            L.append("Mean CII by condition: " + ", ".join([f"{k}={fnum(v)}" for k, v in means.items()]) + ".\n")
            if "TARGET" in means:
                others = [v for k, v in means.items() if k != "TARGET"]
                if others and means["TARGET"] > max(others):
                    L.append("Interpretation: Target has the highest mean CII among available conditions. This supports, but does not prove, a Target-favoring immersion proxy.\n")
        else:
            L.append("No CII table found.\n")
        tti = self.data.get("tti", pd.DataFrame())
        if isinstance(tti, pd.DataFrame) and not tti.empty:
            r = tti.iloc[0]
            col = "TTI_global" if "TTI_global" in tti.columns else tti.columns[0]
            val = as_float(r.get(col))
            desc = "positive/reception-favoring" if val > 0 else "negative/override-favoring or ambiguous"
            L.append(f"TTI global: **{fnum(val)}** ({desc}).\n")
        nupi = self.data.get("nupi", pd.DataFrame())
        if isinstance(nupi, pd.DataFrame) and not nupi.empty:
            r = nupi.iloc[0]
            L.append("NUPI summary found. ")
            for c in ["ALI", "RDI", "NUPI", "classification", "Classification", "nupi_classification"]:
                if c in nupi.columns:
                    L.append(f"`{c}`={r.get(c)}. ")
            L.append("\n")

    def _cet_eet_itp(self, L: List[str]) -> None:
        L.append("\n## 8. CET-R, EET, and MRED-ITP convergence layers\n")
        cet = self.data.get("cet", pd.DataFrame())
        if isinstance(cet, pd.DataFrame) and not cet.empty:
            L.append(f"CET-R residualization summary found with **{len(cet)}** rows. ")
            cv_cols = [c for c in cet.columns if "blocked" in c.lower() or "cv" in c.lower() or "r2" in c.lower() or "r²" in c.lower()]
            if cv_cols:
                vals = []
                for c in cv_cols[:4]:
                    vals.append(f"`{c}` max={fnum(pd.to_numeric(cet[c], errors='coerce').max())}")
                L.append("; ".join(vals) + ". ")
            L.append("Interpretation: if held-out/CV performance is low or negative, stimulus regressors did not explain the target signal well in that model; this is supportive but not confirmatory.\n")
        else:
            L.append("No CET-R residualization table found.\n")
        eet = self.data.get("eet", pd.DataFrame())
        if isinstance(eet, pd.DataFrame) and not eet.empty:
            sim_cols = [c for c in eet.columns if "similarity" in c.lower() or "cosine" in c.lower() or "echo" in c.lower()]
            if sim_cols:
                c = sim_cols[0]
                top = eet.sort_values(c, ascending=False).head(1).iloc[0]
                L.append(f"EET table found. Highest `{c}` is **{fnum(top.get(c))}** at anchor `{top.get('anchor_id','n/a')}` vs `{top.get('comparison','n/a')}`. This is state-vector resemblance, not proof of replay.\n")
        itp = self.data.get("mred_itp", pd.DataFrame())
        if isinstance(itp, pd.DataFrame) and not itp.empty:
            acg = int(itp["ACG_candidate"].apply(as_bool).sum()) if "ACG_candidate" in itp.columns else "n/a"
            ocu = int(itp["OCU_candidate"].apply(as_bool).sum()) if "OCU_candidate" in itp.columns else "n/a"
            L.append(f"MRED-ITP table found: ACG candidates = **{acg}**, OCU candidates = **{ocu}**. This layer is convergence/falsification, not proof.\n")

    def _override_modules(self, L: List[str]) -> None:
        L.append("\n## 9. Override-task diagnostics: OCM/RSM/CVB/Squint\n")
        ocm = self.data.get("ocm_rsm", pd.DataFrame())
        if isinstance(ocm, pd.DataFrame) and not ocm.empty:
            L.append(f"Override cue-task table found with **{len(ocm)}** rows. ")
            for c in ["ocm_event", "OCM_event", "cue_update_event", "latent_guess_risk", "compute_stall_score"]:
                if c in ocm.columns:
                    if ocm[c].dtype == bool or set(ocm[c].dropna().unique()).issubset({0,1,True,False}):
                        L.append(f"`{c}` count={int(ocm[c].apply(as_bool).sum())}. ")
                    else:
                        L.append(f"mean `{c}`={fnum(pd.to_numeric(ocm[c], errors='coerce').mean())}. ")
            L.append("\n")
        else:
            L.append("No OCM/RSM/CVB/Squint table found, or this run did not support override microstate analysis.\n")
        corr = self.data.get("rsm_corr", pd.DataFrame())
        if isinstance(corr, pd.DataFrame) and not corr.empty:
            L.append(f"RSM correlation summary found with **{len(corr)}** rows. Review strongest arithmetic-load / stall / guess-risk associations directly.\n")

    def _baseline_selfreport(self, L: List[str]) -> None:
        L.append("\n## 10. Baseline2 and self-report context\n")
        b2 = self.data.get("baseline2", pd.DataFrame())
        if isinstance(b2, pd.DataFrame) and not b2.empty:
            L.append(f"Baseline1-vs-Baseline2 summary found with **{len(b2)}** rows. Use this for resolution/recovery interpretations rather than acute peak claims.\n")
        sj = self.data.get("self_final_json")
        if isinstance(sj, dict):
            choices = sj.get("choices", {}) if isinstance(sj.get("choices"), dict) else {}
            ratings = sj.get("ratings", {}) if isinstance(sj.get("ratings"), dict) else {}
            if choices:
                L.append("Final self-report choices: " + ", ".join([f"{k}={v}" for k, v in choices.items()]) + ".\n")
            if ratings:
                L.append("Final self-report ratings: " + ", ".join([f"{k}={v}" for k, v in ratings.items()]) + ".\n")
            note = sj.get("final_scene_note") or sj.get("scene_note")
            if note:
                L.append(f"Final scene note: {note}\n")
        else:
            L.append("No PRAYCG2.0 final master self-report JSON found.\n")

    def _missing_modules(self, L: List[str]) -> None:
        L.append("\n## 11. Availability check\n")
        keys = ["amred_table", "mred_peak_table", "candidate_kht", "cii", "tti", "nupi", "cet", "eet", "mred_itp", "ocm_rsm", "baseline2"]
        for k in keys:
            v = self.data.get(k)
            ok = bool(isinstance(v, pd.DataFrame) and not v.empty)
            L.append(f"- {k}: {'available' if ok else 'not found'}\n")

    def _final(self, L: List[str]) -> None:
        L.append("\n## 12. Conservative final read\n")
        # Use MRED-Peak summary if present.
        mprs = self.data.get("mred_peak_summary", pd.DataFrame())
        if isinstance(mprs, pd.DataFrame) and not mprs.empty:
            r = mprs.iloc[0]
            L.append(f"Primary compressed read: **{r.get('overall_interpretation','n/a')}**. The top acute event is `{r.get('top_peak_anchor_id','n/a')}`; the top delayed-resolution event is `{r.get('top_resolution_anchor_id','n/a')}`.\n")
        else:
            L.append("Primary compressed read is unavailable because MRED-Peak/Resolution has not been run.\n")
        L.append("\nRecommended next check: review QC/timing first, then A-MRED, then MRED-Peak/Resolution, then secondary summaries. Do not interpret secondary/exploratory modules as independent proof when the primary QC or anchor gates fail.\n")


def generate_report(analysis_folder: Path, out_dir: Optional[Path] = None, report_name: str = "praycg_offline_interpretation_report") -> Dict[str, str]:
    rb = ReportBuilder(analysis_folder)
    lines = rb.lines()
    if out_dir is None:
        out_dir = rb.root / "report"
    out_dir.mkdir(parents=True, exist_ok=True)
    md = out_dir / f"{report_name}.md"
    txt = out_dir / f"{report_name}.txt"
    js = out_dir / f"{report_name}.json"
    content = "\n".join(lines).replace("\n\n\n", "\n\n")
    md.write_text(content, encoding="utf-8")
    txt.write_text(content, encoding="utf-8")
    js.write_text(json.dumps({"version": VERSION, "analysis_folder": str(rb.root), "report_markdown": str(md), "report_text": str(txt)}, indent=2), encoding="utf-8")
    return {"markdown": str(md), "text": str(txt), "json": str(js)}


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate offline rule-based PRAYCG interpretation report from Master Suite output folder.")
    ap.add_argument("--analysis-folder", required=True, help="Master Comprehensive Suite output folder or tables folder.")
    ap.add_argument("--out-dir", default=None, help="Report output folder. Defaults to <analysis-folder>/report.")
    ap.add_argument("--report-name", default="praycg_offline_interpretation_report", help="Base filename without extension.")
    ap.add_argument("--project-name", default="", help="Optional label accepted for launcher compatibility; content is inferred from analysis folder.")
    args = ap.parse_args()
    result = generate_report(Path(args.analysis_folder), Path(args.out_dir) if args.out_dir else None, args.report_name)
    print(json.dumps({"status": "OK", "outputs": result}, indent=2))


if __name__ == "__main__":
    main()
