#!/usr/bin/env python3
"""
PR-AYC-G v1.6L / PRAYCG1.6L PsychoPy + LSL runner with LSL-hardened marker capture.

Major v1.6L changes
--------------------
HARDENS LSL marker capture. The previous 1.6J runner could create a local JSON/CSV event log
while LabRecorder failed to record StasisMarkers into the XDF if recording started before the
marker outlet existed. Version 1.6L brings the marker outlet online before the LabRecorder
hold screen, sends repeated preflight ping markers, uses a unique source_id per run, timestamps
samples with pylsl.local_clock(), and explicitly instructs the operator to click LabRecorder
Update/Start only after the StasisMarkers stream is online. It preserves the 1.6J report/sum
input markers, stillness resets, channel-map markers, cue markers, and objective sum scoring.

Version 1.6L makes the LabRecorder preflight hold windowed instead of fullscreen.
This prevents the operator from being trapped in a fullscreen black PsychoPy menu while trying
to click LabRecorder Update/Start. Fullscreen begins only after LabRecorder is recording.

Run context
-----------
Run this script in PsychoPy Coder/Standalone after pylsl is installed in the PsychoPy
Python environment. Sensor bridges such as OpenBCI, Polar, and Vernier should already
be streaming to LSL and LabRecorder should NOT be started until the script displays the LSL preflight hold screen and StasisMarkers is visible.

Expected media setup
--------------------
- control_video: preferably phase-scrambled from the cue-embedded target video.
- target_video: cue-embedded intact target video.
- override_video: bit-identical copy of target_video.
- cue_schedule_json: generated by praycg_v1_6J_embed_numbers.py.

The control, target, and override files can still be manually selected in the GUI.
"""

from __future__ import annotations

import csv
import json
import os
import re
import time
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from pylsl import StreamInfo, StreamOutlet, local_clock, resolve_byprop
from psychopy import core, event, gui, logging, visual
from psychopy.constants import FINISHED


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

STANDARD_RATING_ITEMS: Tuple[str, ...] = (
    "Meaning",
    "Empathy",
    "Absorption",
    "StoryActiveWashout",
    "EmotionalAfterglow",
    "AnalyticEffort",
    "TaskCompliance",
    "OverrideLeakage",
    "FatigueDiscomfort",
    "MindWandering",
    "ProtocolThoughts",
    "NumberCueDistraction",
)

REQUIRED_STREAMS_DEFAULT: Tuple[str, ...] = (
    "obci_eeg1",
    "StasisMarkers",  # This stream is created by the script itself; checked after outlet setup.
)

OPTIONAL_STREAMS_DEFAULT: Tuple[str, ...] = (
    "PolarHRV",
    "PolarECG",
    "VernierRespirationBelt",
)

# v1.6J artifact-censoring defaults. These are written into the event log as
# processing guidance; analysis scripts should still make their own exclusions explicit.
MIN_STILLNESS_RESET_SEC = 5.0
MAX_STILLNESS_RESET_SEC = 10.0
DEFAULT_STILLNESS_RESET_SEC = 8.0
REPORT_INPUT_EXCLUSION_PREPAD_SEC = 3.0
REPORT_INPUT_EXCLUSION_POSTPAD_SEC = 5.0

# Fixed PR-AYC-G 16-channel montage recommended for the OpenBCI Cyton+Daisy stack.
# These markers are emitted at SETUP so the XDF file contains an explicit channel map.
# If the operator cannot defend the wiring, set channel_map_confirmed=False or confidence=UNKNOWN.
PRAYCG16_FIXED_CHANNEL_MAP: Tuple[Tuple[int, str, str], ...] = (
    (1, "Fz", "frontal_analytic_lock"),
    (2, "Cz", "central_anchor"),
    (3, "Pz", "parietal_integration"),
    (4, "F3", "left_frontal"),
    (5, "F4", "right_frontal"),
    (6, "C3", "left_central"),
    (7, "C4", "right_central"),
    (8, "P3", "left_parietal"),
    (9, "P4", "right_parietal"),
    (10, "T5", "left_posterior_temporal"),
    (11, "T6", "right_posterior_temporal"),
    (12, "O1", "left_visual_control"),
    (13, "O2", "right_visual_control"),
    (14, "T3", "left_jaw_temporal_sentinel"),
    (15, "T4", "right_jaw_temporal_sentinel"),
    (16, "Fp1", "blink_eye_sentinel"),
)


@dataclass
class CueEvent:
    cue_index: int
    value: int
    start_sec: float
    end_sec: float


class EventLogger:
    def __init__(self, log_dir: Path, participant_id: str, session_id: str, run_label: str) -> None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_pid = sanitize_for_filename(participant_id or "P001")
        safe_sid = sanitize_for_filename(session_id or "S001")
        safe_run = sanitize_for_filename(run_label or "run")
        self.log_dir = log_dir
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.csv_path = self.log_dir / f"PRAYCG_v1_6L_{safe_pid}_{safe_sid}_{safe_run}_{timestamp}_events.csv"
        self.json_path = self.log_dir / f"PRAYCG_v1_6L_{safe_pid}_{safe_sid}_{safe_run}_{timestamp}_events.json"
        self.rows: List[Dict[str, Any]] = []
        self.csv_file = self.csv_path.open("w", newline="", encoding="utf-8")
        self.writer = csv.DictWriter(
            self.csv_file,
            fieldnames=["marker", "phase", "note", "lsl_time", "unix_time", "psychopy_time"],
        )
        self.writer.writeheader()

    def log(self, marker: str, phase: str = "", note: str = "", lsl_time_override: Optional[float] = None) -> None:
        row = {
            "marker": marker,
            "phase": phase,
            "note": note,
            "lsl_time": float(lsl_time_override) if lsl_time_override is not None else local_clock(),
            "unix_time": time.time(),
            "psychopy_time": core.getTime(),
        }
        self.rows.append(row)
        self.writer.writerow(row)
        self.csv_file.flush()

    def close(self) -> None:
        self.csv_file.flush()
        self.csv_file.close()
        self.json_path.write_text(json.dumps(self.rows, indent=2), encoding="utf-8")


def sanitize_for_filename(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_") or "NA"


def sanitize_marker_part(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_") or "NA"


def push_marker(outlet: StreamOutlet, logger: EventLogger, marker: str, phase: str = "", note: str = "") -> None:
    """Push one marker to LSL and mirror it to the local CSV/JSON log.

    The local log is useful, but the XDF stream is the authority for physiology alignment.
    Version 1.6L therefore timestamps the LSL sample explicitly with pylsl.local_clock()
    and requests pushthrough when the installed pylsl version supports it.
    """
    marker = sanitize_marker_part(marker)
    ts = local_clock()
    try:
        outlet.push_sample([marker], timestamp=ts, pushthrough=True)
    except TypeError:
        # Older pylsl builds may not expose pushthrough as a keyword.
        outlet.push_sample([marker], timestamp=ts)
    logger.log(marker, phase=phase, note=note, lsl_time_override=ts)
    print(f"MARKER {marker} | lsl_time={ts:.6f} | phase={phase} | note={note}")




def write_channel_map_csv(
    logger: EventLogger,
    rows: Sequence[Tuple[int, str, str]],
    *,
    map_label: str,
    confirmed: bool,
    confidence: str,
    notes: str = "",
) -> Path:
    out = logger.log_dir / f"{logger.csv_path.stem}_channel_map.csv"
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["openbci_channel", "electrode_location", "roi", "map_label", "confirmed", "confidence", "notes"],
        )
        writer.writeheader()
        for ch, electrode, roi in rows:
            writer.writerow({
                "openbci_channel": ch,
                "electrode_location": electrode,
                "roi": roi,
                "map_label": map_label,
                "confirmed": int(bool(confirmed)),
                "confidence": confidence,
                "notes": notes,
            })
    return out


def emit_channel_map_markers(
    outlet: StreamOutlet,
    logger: EventLogger,
    rows: Sequence[Tuple[int, str, str]],
    *,
    map_label: str,
    confirmed: bool,
    confidence: str,
    notes: str = "",
) -> None:
    """Emit parseable LSL markers documenting OpenBCI channel -> electrode mapping."""
    clean_label = sanitize_marker_part(map_label)
    clean_conf = sanitize_marker_part(confidence.upper())
    csv_path = write_channel_map_csv(logger, rows, map_label=map_label, confirmed=confirmed, confidence=confidence, notes=notes)

    push_marker(outlet, logger, "CHANNEL_MAP_START", phase="SETUP", note=str(csv_path))
    push_marker(outlet, logger, f"CHANNEL_MAP_LABEL_{clean_label}", phase="SETUP", note=map_label)
    push_marker(outlet, logger, f"CHANNEL_MAP_CONFIRMED_{'TRUE' if confirmed else 'FALSE'}", phase="SETUP", note=notes)
    push_marker(outlet, logger, f"CHANNEL_MAP_CONFIDENCE_{clean_conf}", phase="SETUP", note=confidence)
    if not confirmed or clean_conf in {"UNKNOWN", "UNCONFIRMED", "NONE"}:
        push_marker(outlet, logger, "CHANNEL_MAP_UNCONFIRMED_DO_NOT_USE_ROI", phase="SETUP", note=notes)
    for ch, electrode, roi in rows:
        push_marker(
            outlet,
            logger,
            f"CHANNEL_MAP_CH{int(ch):02d}_{sanitize_marker_part(electrode)}_ROI_{sanitize_marker_part(roi)}",
            phase="SETUP",
            note=f"channel={ch};electrode={electrode};roi={roi};map_label={map_label};confirmed={confirmed};confidence={confidence}",
        )
    push_marker(outlet, logger, "CHANNEL_MAP_END", phase="SETUP", note=str(csv_path))


def check_escape(outlet: StreamOutlet, logger: EventLogger, win: visual.Window, phase: str = "") -> None:
    if "escape" in event.getKeys(keyList=["escape"]):
        push_marker(outlet, logger, "EMERGENCY_KILL", phase=phase)
        logger.close()
        win.close()
        core.quit()


def parse_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    s = str(value).strip().lower()
    return s in {"1", "true", "yes", "y", "on"}


def parse_int(value: Any, default: int) -> int:
    try:
        return int(str(value).strip())
    except Exception:
        return default


def parse_float(value: Any, default: float) -> float:
    try:
        return float(str(value).strip())
    except Exception:
        return default


def clamp_float(value: float, low: float, high: float) -> float:
    return max(low, min(high, float(value)))


def resolve_stream_names(timeout: float = 1.0) -> List[str]:
    streams = resolve_byprop("type", "", timeout=timeout)
    names = []
    for stream in streams:
        try:
            names.append(stream.name())
        except Exception:
            pass
    # resolve_byprop('', '') can be backend-sensitive. Try broad common types if empty.
    if not names:
        for stream_type in ["EEG", "Markers", "HRV", "ECG", "Respiration", "RespirationBelt"]:
            for stream in resolve_byprop("type", stream_type, timeout=0.25):
                try:
                    names.append(stream.name())
                except Exception:
                    pass
    return sorted(set(names))


def load_cue_schedule(path: str) -> Tuple[List[CueEvent], Optional[int], Dict[str, Any]]:
    if not path or not Path(path).exists():
        return [], None, {}
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    cues = []
    for row in payload.get("cue_events", []):
        cues.append(
            CueEvent(
                cue_index=int(row["cue_index"]),
                value=int(row["value"]),
                start_sec=float(row["start_sec"]),
                end_sec=float(row["end_sec"]),
            )
        )
    expected = payload.get("expected_sum", None)
    expected_int = int(expected) if expected is not None and str(expected).strip() else None
    return cues, expected_int, payload


def show_text_and_wait(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    text: str,
    *,
    phase: str,
    marker_prefix: str,
    key_list: Sequence[str] = ("space", "return"),
) -> None:
    push_marker(outlet, logger, f"{marker_prefix}_START", phase=phase)
    stim = visual.TextStim(win, text=text, color="white", height=32, wrapWidth=1550, alignText="center")
    stim.draw()
    win.flip()
    event.clearEvents()
    while True:
        keys = event.getKeys(keyList=list(key_list) + ["escape"])
        if "escape" in keys:
            check_escape(outlet, logger, win, phase=phase)
        if any(k in keys for k in key_list):
            break
        core.wait(0.02)
    win.flip()
    push_marker(outlet, logger, f"{marker_prefix}_END", phase=phase)


def wait_for_right_click(win: visual.Window, outlet: StreamOutlet, logger: EventLogger) -> None:
    """Hold experiment while StasisMarkers is alive so LabRecorder can capture it.

    This fixes the main 1.6J failure mode: starting LabRecorder before the marker
    outlet existed. Do not start LabRecorder before this screen. While this screen is
    visible, the script emits repeated LSL_PREFLIGHT_PING_* markers once per second.
    """
    text = (
        "LSL Marker Stream Is Now Online.\n\n"
        "DO THIS NOW, IN THIS ORDER:\n"
        "1. Open LabRecorder if it is not already open.\n"
        "2. Click UPDATE.\n"
        "3. Confirm these streams are visible and checked:\n"
        "   - StasisMarkers\n"
        "   - obci_eeg1\n"
        "   - PolarHRV if used\n"
        "   - VernierRespirationBelt if used\n"
        "4. Click START in LabRecorder.\n\n"
        "This screen will keep sending LSL_PREFLIGHT_PING markers.\n"
        "This window is intentionally NOT fullscreen so you can Alt-Tab or click LabRecorder.\n"
        "If StasisMarkers is not visible in LabRecorder, stop now and fix it.\n\n"
        "LEFT-CLICK once to focus this screen.\n"
        "RIGHT-CLICK only after LabRecorder is recording StasisMarkers."
    )
    push_marker(outlet, logger, "LSL_PREFLIGHT_HOLD_START", phase="SETUP", note="Start LabRecorder during this hold, not before script launch.")
    msg = visual.TextStim(win, text=text, color="white", height=32, wrapWidth=1600, alignText="center")
    msg.draw()
    win.flip()
    mouse = event.Mouse(win=win)
    mouse.clickReset()
    hold_clock = core.Clock()
    next_ping = 0.0
    ping_n = 0
    while True:
        now = hold_clock.getTime()
        if now >= next_ping:
            ping_n += 1
            push_marker(outlet, logger, f"LSL_PREFLIGHT_PING_{ping_n:03d}", phase="SETUP", note="If LabRecorder records StasisMarkers, this ping should appear in the XDF.")
            next_ping = now + 1.0
        buttons = mouse.getPressed()
        if buttons[2]:
            break
        check_escape(outlet, logger, win, phase="SETUP")
        msg.draw()
        win.flip()
        core.wait(0.03)
    push_marker(outlet, logger, "LSL_PREFLIGHT_HOLD_END", phase="SETUP", note=f"pings_sent={ping_n}")
    win.flip()
    core.wait(0.5)

def return_to_stillness(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    duration: float,
    reason: str = "",
) -> None:
    """Insert a non-analysis stillness reset after typing/report movement.

    This block is deliberately bracketed with broad and phase-specific markers. Analysis
    scripts can hard-exclude the report/sum windows and use this reset as a settling buffer
    before the next analyzable physiology block.
    """
    duration = clamp_float(duration, MIN_STILLNESS_RESET_SEC, MAX_STILLNESS_RESET_SEC)
    note = f"duration_sec={duration:.3f};reason={reason}"
    push_marker(outlet, logger, "RETURN_TO_STILLNESS_START", phase=phase_name, note=note)
    push_marker(outlet, logger, f"RETURN_TO_STILLNESS_{phase_name}_START", phase=phase_name, note=note)

    reset_clock = core.Clock()
    stim = visual.TextStim(win, text="", color="white", height=34, wrapWidth=1500, alignText="center")
    while reset_clock.getTime() < duration:
        remaining = max(0.0, duration - reset_clock.getTime())
        stim.text = (
            "Return to stillness.\n\n"
            "Sit back in the chair. Put hands in lap.\n"
            "Relax jaw, shoulders, neck, forehead, and tongue.\n"
            "Eyes on the cross. Breathe normally.\n\n"
            f"Stillness reset: {remaining:0.1f} seconds"
        )
        stim.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
        core.wait(0.02)
    win.flip()
    push_marker(outlet, logger, f"RETURN_TO_STILLNESS_{phase_name}_END", phase=phase_name, note=note)
    push_marker(outlet, logger, "RETURN_TO_STILLNESS_END", phase=phase_name, note=note)


def run_baseline(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    fixation: visual.TextStim,
    *,
    duration: float,
    phase_name: str,
) -> None:
    push_marker(outlet, logger, f"{phase_name}_START", phase=phase_name)
    clock = core.Clock()
    while clock.getTime() < duration:
        fixation.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
    push_marker(outlet, logger, f"{phase_name}_END", phase=phase_name)


def _get_movie_duration(mov: Any) -> Optional[float]:
    for attr in ("duration", "_duration"):
        try:
            val = getattr(mov, attr)
            if val is not None and float(val) > 0:
                return float(val)
        except Exception:
            pass
    return None


def play_video(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    video_path: str,
    *,
    phase_name: str,
    cue_events: Sequence[CueEvent] = (),
    emit_cue_markers: bool = True,
) -> None:
    path = Path(video_path).expanduser()
    if not path.exists():
        push_marker(outlet, logger, f"ERROR_MISSING_{phase_name}_MEDIA", phase=phase_name, note=str(path))
        raise FileNotFoundError(path)

    push_marker(outlet, logger, f"{phase_name}_LOAD_OK", phase=phase_name, note=str(path))
    mov = visual.MovieStim(win, str(path), size=(1920, 1080), flipVert=False, flipHoriz=False, loop=False)
    duration = _get_movie_duration(mov)
    timeout_limit = (duration + 0.35) if duration else 9999.0

    # First flip after loading gives a clean visual reset before the start marker.
    win.flip()
    core.wait(0.05)

    push_marker(outlet, logger, f"{phase_name}_START", phase=phase_name)
    try:
        mov.play()
    except Exception:
        pass

    play_clock = core.Clock()
    cue_start_sent = set()
    cue_end_sent = set()

    while mov.status != FINISHED:
        t = play_clock.getTime()
        if emit_cue_markers:
            for cue in cue_events:
                if cue.cue_index not in cue_start_sent and t >= cue.start_sec:
                    push_marker(
                        outlet,
                        logger,
                        f"{phase_name}_CUE_{cue.cue_index:03d}_VALUE_{cue.value}_START",
                        phase=phase_name,
                        note=f"t={cue.start_sec:.3f}",
                    )
                    cue_start_sent.add(cue.cue_index)
                if cue.cue_index not in cue_end_sent and t >= cue.end_sec:
                    push_marker(
                        outlet,
                        logger,
                        f"{phase_name}_CUE_{cue.cue_index:03d}_VALUE_{cue.value}_END",
                        phase=phase_name,
                        note=f"t={cue.end_sec:.3f}",
                    )
                    cue_end_sent.add(cue.cue_index)
        mov.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
        if play_clock.getTime() >= timeout_limit:
            push_marker(outlet, logger, f"{phase_name}_TIMEOUT_BREAK", phase=phase_name)
            break
    try:
        mov.stop()
    except Exception:
        pass
    push_marker(outlet, logger, f"{phase_name}_END", phase=phase_name)
    win.flip()


def collect_numeric_response(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    expected_sum: Optional[int],
    reward_text: str = "",
) -> Tuple[Optional[int], Optional[bool]]:
    push_marker(outlet, logger, "SUM_INPUT_START", phase=phase_name, note=phase_name)
    push_marker(outlet, logger, f"SUM_INPUT_{phase_name}_START", phase=phase_name)
    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_START", phase=phase_name)
    response = ""
    prompt = visual.TextStim(win, text="", color="white", height=38, wrapWidth=1500, alignText="center")
    event.clearEvents()

    while True:
        prompt.text = (
            "Contextual Override Sum\n\n"
            "Type the running sum of all numbers you saw.\n"
            "Press ENTER when done. Backspace edits.\n\n"
            f"Current answer: {response if response else '_'}"
        )
        prompt.draw()
        win.flip()
        keys = event.getKeys(keyList=list("0123456789") + ["backspace", "return", "enter", "escape"])
        for k in keys:
            if k == "escape":
                check_escape(outlet, logger, win, phase=phase_name)
            elif k == "backspace":
                response = response[:-1]
            elif k in ("return", "enter"):
                if response.strip():
                    try:
                        numeric = int(response)
                    except ValueError:
                        numeric = None
                    correct = (numeric == expected_sum) if expected_sum is not None and numeric is not None else None
                    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_{numeric if numeric is not None else 'INVALID'}", phase=phase_name)
                    if expected_sum is not None:
                        push_marker(outlet, logger, f"RESPONSE_{phase_name}_EXPECTED_SUM_{expected_sum}", phase=phase_name)
                    if correct is not None:
                        push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_CORRECT_{1 if correct else 0}", phase=phase_name)
                    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_END", phase=phase_name)
                    push_marker(outlet, logger, f"SUM_INPUT_{phase_name}_END", phase=phase_name)
                    push_marker(outlet, logger, "SUM_INPUT_END", phase=phase_name, note=phase_name)

                    if correct and reward_text.strip():
                        msg = visual.TextStim(win, text=reward_text, color="white", height=38, wrapWidth=1500, alignText="center")
                        msg.draw()
                        win.flip()
                        push_marker(outlet, logger, f"REWARD_DISPLAYED_{phase_name}", phase=phase_name, note=reward_text.strip())
                        core.wait(2.0)
                    else:
                        msg_text = "Response recorded."
                        if correct is False:
                            msg_text = "Response recorded."
                        msg = visual.TextStim(win, text=msg_text, color="white", height=38, wrapWidth=1500, alignText="center")
                        msg.draw()
                        win.flip()
                        core.wait(1.0)
                    return numeric, correct
            elif k.isdigit():
                # Prevent runaway accidental input.
                if len(response) < 8:
                    response += k
        core.wait(0.02)


def collect_rating(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    item: str,
) -> int:
    text = (
        f"{item}\n\n"
        "Rate 0-9.\n"
        "0 = none / not at all\n"
        "9 = very high / very strong\n\n"
        "Press one number key."
    )
    stim = visual.TextStim(win, text=text, color="white", height=38, wrapWidth=1500, alignText="center")
    stim.draw()
    win.flip()
    event.clearEvents()
    while True:
        keys = event.getKeys(keyList=list("0123456789") + ["escape"])
        if "escape" in keys:
            check_escape(outlet, logger, win, phase=phase_name)
        for k in keys:
            if k.isdigit():
                rating = int(k)
                push_marker(outlet, logger, f"RATING_{phase_name}_{item}_{rating}", phase=phase_name)
                core.wait(0.15)
                return rating
        core.wait(0.02)


def collect_phase_ratings(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    items: Sequence[str] = STANDARD_RATING_ITEMS,
) -> Dict[str, int]:
    push_marker(outlet, logger, "REPORT_INPUT_START", phase=phase_name, note=phase_name)
    push_marker(outlet, logger, f"REPORT_INPUT_{phase_name}_START", phase=phase_name)
    push_marker(outlet, logger, f"RATINGS_{phase_name}_START", phase=phase_name)
    results: Dict[str, int] = {}
    for item in items:
        results[item] = collect_rating(win, outlet, logger, phase_name=phase_name, item=item)
    result_note = json.dumps(results, sort_keys=True)
    push_marker(outlet, logger, f"RATINGS_{phase_name}_END", phase=phase_name, note=result_note)
    push_marker(outlet, logger, f"REPORT_INPUT_{phase_name}_END", phase=phase_name, note=result_note)
    push_marker(outlet, logger, "REPORT_INPUT_END", phase=phase_name, note=result_note)
    return results


def collect_gui_config() -> Dict[str, Any]:
    dlg = gui.Dlg(title="PRAYCG1.6L Pre-Flight")
    dlg.addText("Experiment identity")
    dlg.addField("Participant ID:", "P001")
    dlg.addField("Session ID:", "S001")
    dlg.addField("Run label:", "run001")
    dlg.addText("Media files")
    dlg.addField("Control video path:", "stimulus_control_cued_scrambled.mp4")
    dlg.addField("Target video path:", "stimulus_target_cued_v1_6J.mp4")
    dlg.addField("Override video path:", "stimulus_override_cued_v1_6J.mp4")
    dlg.addField("Cue schedule JSON:", "cue_schedule_v1_6J.json")
    dlg.addField("Expected sum override (blank = load from schedule):", "")
    dlg.addText("Timing")
    dlg.addField("Baseline seconds:", "120")
    dlg.addField("Washout seconds:", "120")
    dlg.addField("Stillness reset seconds after report/sum input (5-10):", "8")
    dlg.addText("EEG channel map")
    dlg.addField("Use standard PRAYCG16 fixed channel map True/False:", "True")
    dlg.addField("Channel map confirmed True/False:", "False")
    dlg.addField("Channel map confidence LOCKED/PROBABLE/UNKNOWN:", "UNKNOWN")
    dlg.addField("Channel map label:", "PRAYCG16_FIXED_ORDER_v1")
    dlg.addField("Channel map notes:", "Set confirmed=True only after wire-to-electrode map is photographed or physically traced.")
    dlg.addText("Display and logging")
    dlg.addField("Fullscreen True/False:", "True")
    dlg.addField("Screen index:", "0")
    dlg.addField("Log directory:", "praycg_run_logs")
    dlg.addField("Reward text if correct (blank = no reward):", "Correct. Response logged.")
    dlg.addText("Do NOT start LabRecorder before pressing OK. After OK, StasisMarkers will come online and a hold screen will tell you to click Update/Start in LabRecorder.")
    dlg.show()
    if not dlg.OK:
        core.quit()
    vals = dlg.data
    return {
        "participant_id": vals[0],
        "session_id": vals[1],
        "run_label": vals[2],
        "control_video": vals[3],
        "target_video": vals[4],
        "override_video": vals[5],
        "cue_schedule_json": vals[6],
        "expected_sum_manual": vals[7],
        "baseline_seconds": parse_float(vals[8], 120.0),
        "washout_seconds": parse_float(vals[9], 120.0),
        "stillness_reset_seconds": clamp_float(parse_float(vals[10], DEFAULT_STILLNESS_RESET_SEC), MIN_STILLNESS_RESET_SEC, MAX_STILLNESS_RESET_SEC),
        "use_standard_channel_map": parse_bool(vals[11]),
        "channel_map_confirmed": parse_bool(vals[12]),
        "channel_map_confidence": str(vals[13]).strip().upper() or "UNKNOWN",
        "channel_map_label": str(vals[14]).strip() or "PRAYCG16_FIXED_ORDER_v1",
        "channel_map_notes": str(vals[15]).strip(),
        "fullscreen": parse_bool(vals[16]),
        "screen_index": parse_int(vals[17], 0),
        "log_dir": vals[18],
        "reward_text": vals[19],
    }


def run_full_experiment() -> None:
    logging.console.setLevel(logging.WARNING)
    cfg = collect_gui_config()

    log_dir = Path(str(cfg["log_dir"])).expanduser().resolve()
    logger = EventLogger(log_dir, str(cfg["participant_id"]), str(cfg["session_id"]), str(cfg["run_label"]))

    source_id = f"praycg_stasismarkers_{sanitize_for_filename(str(cfg['participant_id']))}_{sanitize_for_filename(str(cfg['session_id']))}_{uuid.uuid4().hex[:10]}"
    info = StreamInfo("StasisMarkers", "Markers", 1, 0, "string", source_id)
    desc = info.desc()
    desc.append_child_value("protocol", "PRAYCG")
    desc.append_child_value("protocol_version", "1.6L")
    desc.append_child_value("source_id", source_id)
    desc.append_child_value("marker_capture_rule", "Start LabRecorder only after LSL_PREFLIGHT_HOLD_START appears and StasisMarkers is visible.")
    outlet = StreamOutlet(info, chunk_size=1, max_buffered=3600)
    core.wait(0.75)
    logger.log("LOCAL_LOG_CREATED", phase="SETUP", note=str(logger.csv_path))
    push_marker(outlet, logger, "STASIS_MARKER_STREAM_ONLINE", phase="SETUP", note=source_id)
    push_marker(outlet, logger, "PRAYCG_VERSION_1.6L", phase="SETUP")
    push_marker(outlet, logger, "STASIS_MARKER_SOURCE_ID_RECORDED", phase="SETUP", note=source_id)
    push_marker(outlet, logger, "LABRECORDER_START_AFTER_THIS_MARKER_STREAM_IS_ONLINE", phase="SETUP")
    push_marker(outlet, logger, f"STILLNESS_RESET_SECONDS_{float(cfg['stillness_reset_seconds']):.1f}", phase="SETUP")
    push_marker(outlet, logger, f"REPORT_INPUT_EXCLUSION_PREPAD_SEC_{REPORT_INPUT_EXCLUSION_PREPAD_SEC:.1f}", phase="SETUP")
    push_marker(outlet, logger, f"REPORT_INPUT_EXCLUSION_POSTPAD_SEC_{REPORT_INPUT_EXCLUSION_POSTPAD_SEC:.1f}", phase="SETUP")

    if bool(cfg.get("use_standard_channel_map", True)):
        emit_channel_map_markers(
            outlet,
            logger,
            PRAYCG16_FIXED_CHANNEL_MAP,
            map_label=str(cfg.get("channel_map_label", "PRAYCG16_FIXED_ORDER_v1")),
            confirmed=bool(cfg.get("channel_map_confirmed", False)),
            confidence=str(cfg.get("channel_map_confidence", "UNKNOWN")),
            notes=str(cfg.get("channel_map_notes", "")),
        )
    else:
        push_marker(outlet, logger, "CHANNEL_MAP_NOT_EMITTED", phase="SETUP", note="use_standard_channel_map=False")
        push_marker(outlet, logger, "CHANNEL_MAP_UNCONFIRMED_DO_NOT_USE_ROI", phase="SETUP", note="No channel map emitted.")

    cue_events, expected_sum_from_schedule, cue_payload = load_cue_schedule(str(cfg["cue_schedule_json"]))
    expected_sum: Optional[int] = expected_sum_from_schedule
    if str(cfg["expected_sum_manual"]).strip():
        expected_sum = parse_int(cfg["expected_sum_manual"], expected_sum_from_schedule or -1)
    if expected_sum is not None and expected_sum >= 0:
        push_marker(outlet, logger, f"CUE_SCHEDULE_EXPECTED_SUM_{expected_sum}", phase="SETUP")
    if cue_events:
        push_marker(outlet, logger, f"CUE_SCHEDULE_LOADED_N_{len(cue_events)}", phase="SETUP", note=str(cfg["cue_schedule_json"]))
    else:
        push_marker(outlet, logger, "CUE_SCHEDULE_NOT_LOADED", phase="SETUP", note=str(cfg["cue_schedule_json"]))

    # Stream inventory snapshot. This is only advisory; LabRecorder is the ground truth.
    stream_names = resolve_stream_names(timeout=0.75)
    logger.log("STREAM_INVENTORY", phase="SETUP", note=",".join(stream_names))

    win = None

    # v1.6L correction: keep the LabRecorder preflight as a normal window so the
    # operator can Alt-Tab / click LabRecorder Update / Start without being trapped
    # inside a fullscreen black PsychoPy window. The StasisMarkers outlet is already
    # online at this point and LSL_PREFLIGHT_PING markers are being emitted.
    preflight_win = visual.Window(
        size=(980, 680),
        fullscr=False,
        screen=0,
        units="pix",
        color=[-1, -1, -1],
        allowGUI=True,
    )
    try:
        wait_for_right_click(preflight_win, outlet, logger)
    finally:
        try:
            preflight_win.close()
        except Exception:
            pass
    core.wait(0.35)

    # Only now enter the experiment display mode. This is the first fullscreen window.
    win = visual.Window(
        size=(1920, 1080),
        fullscr=bool(cfg["fullscreen"]),
        screen=int(cfg["screen_index"]),
        units="pix",
        color=[-1, -1, -1],
        allowGUI=False,
    )
    fixation = visual.TextStim(win, text="+", color="white", height=56)

    try:
        push_marker(outlet, logger, "PROTOCOL_SEQUENCE_START", phase="PROTOCOL")

        run_baseline(win, outlet, logger, fixation, duration=float(cfg["baseline_seconds"]), phase_name="BASELINE_1")

        show_text_and_wait(
            win,
            outlet,
            logger,
            "Control block.\n\nWatch the screen naturally. Keep your eyes forward and stay relaxed.\n\nPress SPACE to continue.",
            phase="CONTROL_1",
            marker_prefix="CONTROL_1_INSTRUCTION",
        )
        play_video(win, outlet, logger, str(cfg["control_video"]), phase_name="CONTROL_1", cue_events=(), emit_cue_markers=False)
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_1")
        collect_phase_ratings(win, outlet, logger, phase_name="CONTROL_1_AFTER_WASHOUT_1")
        return_to_stillness(
            win, outlet, logger,
            phase_name="CONTROL_1_AFTER_WASHOUT_1",
            duration=float(cfg["stillness_reset_seconds"]),
            reason="after_control_report_before_target_instruction",
        )

        show_text_and_wait(
            win,
            outlet,
            logger,
            (
                "Target block.\n\n"
                "Watch naturally. Let the story land if it lands.\n"
                "Small numbers may appear. Ignore them. Do not count them.\n\n"
                "Press SPACE to continue."
            ),
            phase="TARGET_1",
            marker_prefix="TARGET_1_INSTRUCTION",
        )
        play_video(win, outlet, logger, str(cfg["target_video"]), phase_name="TARGET_1", cue_events=cue_events, emit_cue_markers=True)
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_2")
        collect_phase_ratings(win, outlet, logger, phase_name="TARGET_1_AFTER_WASHOUT_2")
        return_to_stillness(
            win, outlet, logger,
            phase_name="TARGET_1_AFTER_WASHOUT_2",
            duration=float(cfg["stillness_reset_seconds"]),
            reason="after_target_report_before_override_instruction",
        )

        expected_text = "" if expected_sum is None else "The correct answer is stored privately and will be checked after you respond."
        show_text_and_wait(
            win,
            outlet,
            logger,
            (
                "Contextual Override block.\n\n"
                "Watch the same story, but this time perform the counting task.\n"
                "Every time a number appears, add it to a running sum in your head.\n"
                "You will type the final sum immediately after the video.\n"
                f"{expected_text}\n\n"
                "Press SPACE to continue."
            ),
            phase="CONTEXTUAL_OVERRIDE_1",
            marker_prefix="CONTEXTUAL_OVERRIDE_1_INSTRUCTION",
        )
        if expected_sum is not None:
            push_marker(outlet, logger, f"CONTEXTUAL_OVERRIDE_1_EXPECTED_SUM_{expected_sum}", phase="CONTEXTUAL_OVERRIDE_1")
        play_video(
            win,
            outlet,
            logger,
            str(cfg["override_video"]),
            phase_name="CONTEXTUAL_OVERRIDE_1",
            cue_events=cue_events,
            emit_cue_markers=True,
        )
        collect_numeric_response(
            win,
            outlet,
            logger,
            phase_name="CONTEXTUAL_OVERRIDE_1",
            expected_sum=expected_sum,
            reward_text=str(cfg["reward_text"]),
        )
        return_to_stillness(
            win, outlet, logger,
            phase_name="CONTEXTUAL_OVERRIDE_1_SUM_ENTRY",
            duration=float(cfg["stillness_reset_seconds"]),
            reason="after_sum_input_before_washout_3",
        )
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_3")
        collect_phase_ratings(win, outlet, logger, phase_name="OVERRIDE_1_AFTER_WASHOUT_3")

        push_marker(outlet, logger, "PROTOCOL_SEQUENCE_END", phase="PROTOCOL")
    finally:
        logger.close()
        try:
            if win is not None:
                win.close()
        except Exception:
            pass
        core.quit()


if __name__ == "__main__":
    run_full_experiment()
