#!/usr/bin/env python3
"""
PR-AYC-G v1.8 / PRAYCG1.8 PsychoPy + LSL runner with browse-file media selection and LSL-hardened marker capture.

Major v1.8 changes
--------------------
ADDS a browse-file preflight GUI for selecting Control, Target, Contextual Override, and cue schedule JSON.
It also preserves the v1.6R LSL hardening.

HARDENS LSL marker capture. The previous 1.6J runner could create a local JSON/CSV event log
while LabRecorder failed to record StasisMarkers into the XDF if recording started before the
marker outlet existed. Version 1.8 brings the marker outlet online before the LabRecorder
hold screen, sends repeated preflight ping markers, uses a unique source_id per run, timestamps
samples with pylsl.local_clock(), and explicitly instructs the operator to click LabRecorder
Update/Start only after the StasisMarkers stream is online. It preserves the 1.6J report/sum
input markers, stillness resets, channel-map markers, cue markers, and objective sum scoring.

Version 1.8 preserves the v1.6R transition-order fix after washout/report periods. The intended flow is now:
self-report input -> press SPACE to proceed -> 8-10 second stillness countdown -> next clip starts automatically.
This prevents the subject from pressing a key immediately before the next analyzable video block.

Version 1.6L made the LabRecorder preflight hold windowed instead of fullscreen.
This prevents the operator from being trapped in a fullscreen black PsychoPy menu while trying
to click LabRecorder Update/Start. Fullscreen begins only after LabRecorder is recording.

Run context
-----------
Run this script in PsychoPy Coder/Standalone after pylsl is installed in the PsychoPy
Python environment. Sensor bridges such as OpenBCI, Polar, and Vernier should already
be streaming to LSL and LabRecorder should NOT be started until the script displays the LSL preflight hold screen and StasisMarkers is visible.

Expected media setup
--------------------
- control_video: preferably phase-scrambled from the cue-embedded target video.
- target_video: cue-embedded intact target video.
- override_video: bit-identical copy of target_video.
- cue_schedule_json: generated by PRAYCG MediaPrep v1.6M+ / v1.6Q+ cue pipeline.

The control, target, override, and event cue JSON files are selected using Browse buttons in the initial GUI.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import re
import time
import uuid
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from pylsl import StreamInfo, StreamOutlet, StreamInlet, local_clock, resolve_byprop
from psychopy import core, event, gui, logging, visual
from psychopy.constants import FINISHED


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

STANDARD_RATING_ITEMS: Tuple[str, ...] = (
    "Meaning",
    "Empathy",
    "Absorption",
    "StoryActiveWashout",
    "EmotionalAfterglow",
    "AnalyticEffort",
    "TaskCompliance",
    "OverrideLeakage",
    "FatigueDiscomfort",
    "MindWandering",
    "ProtocolThoughts",
    "NumberCueDistraction",
)

REQUIRED_STREAMS_DEFAULT: Tuple[str, ...] = (
    "obci_eeg1",
    "StasisMarkers",  # This stream is created by the script itself; checked after outlet setup.
)

OPTIONAL_STREAMS_DEFAULT: Tuple[str, ...] = (
    "PolarHRV",
    "PolarECG",
    "VernierRespirationBelt",
    "OpenBCIStatusMarkers",
)

# v1.6J artifact-censoring defaults. These are written into the event log as
# processing guidance; analysis scripts should still make their own exclusions explicit.
MIN_STILLNESS_RESET_SEC = 5.0
MAX_STILLNESS_RESET_SEC = 10.0
DEFAULT_STILLNESS_RESET_SEC = 8.0
DEFAULT_FINAL_REFLECTION_BASELINE_SEC = 120.0
DEFAULT_MOVIE_SAFE_FIT_FRACTION = 0.92
REPORT_INPUT_EXCLUSION_PREPAD_SEC = 3.0
REPORT_INPUT_EXCLUSION_POSTPAD_SEC = 5.0

# Fixed PR-AYC-G 16-channel montage recommended for the OpenBCI Cyton+Daisy stack.
# These markers are emitted at SETUP so the XDF file contains an explicit channel map.
# If the operator cannot defend the wiring, set channel_map_confirmed=False or confidence=UNKNOWN.
PRAYCG16_FIXED_CHANNEL_MAP: Tuple[Tuple[int, str, str], ...] = (
    (1, "Fz", "frontal_analytic_lock"),
    (2, "Cz", "central_anchor"),
    (3, "Pz", "parietal_integration"),
    (4, "F3", "left_frontal"),
    (5, "F4", "right_frontal"),
    (6, "C3", "left_central"),
    (7, "C4", "right_central"),
    (8, "P3", "left_parietal"),
    (9, "P4", "right_parietal"),
    (10, "T5", "left_posterior_temporal"),
    (11, "T6", "right_posterior_temporal"),
    (12, "O1", "left_visual_control"),
    (13, "O2", "right_visual_control"),
    (14, "T3", "left_jaw_temporal_sentinel"),
    (15, "T4", "right_jaw_temporal_sentinel"),
    (16, "Fp1", "blink_eye_sentinel"),
)


# -----------------------------------------------------------------------------
# EEG live watchdog v1.8
# -----------------------------------------------------------------------------

ACTIVE_EEG_WATCHDOG = None

class LSLEEGWatchdog:
    """Lightweight live sample-flow monitor for obci_eeg1.

    This does not replace LabRecorder and does not alter the EEG stream. It opens its
    own LSL inlet and pulls samples only to verify that EEG remains alive during the run.
    It emits StasisMarkers warnings if sample flow becomes unstable.
    """
    def __init__(
        self,
        outlet: StreamOutlet,
        logger: EventLogger,
        *,
        stream_name: str = "obci_eeg1",
        expected_rate_hz: float = 125.0,
        resolve_timeout_sec: float = 2.0,
        warning_gap_sec: float = 1.0,
        invalid_gap_sec: float = 3.0,
        rate_window_sec: float = 10.0,
        rate_warn_hz: float = 115.0,
        rate_invalid_hz: float = 100.0,
        heartbeat_sec: float = 10.0,
        max_pull_samples: int = 512,
    ) -> None:
        self.outlet = outlet
        self.logger = logger
        self.stream_name = stream_name
        self.expected_rate_hz = float(expected_rate_hz)
        self.resolve_timeout_sec = float(resolve_timeout_sec)
        self.warning_gap_sec = float(warning_gap_sec)
        self.invalid_gap_sec = float(invalid_gap_sec)
        self.rate_window_sec = float(rate_window_sec)
        self.rate_warn_hz = float(rate_warn_hz)
        self.rate_invalid_hz = float(rate_invalid_hz)
        self.heartbeat_sec = float(heartbeat_sec)
        self.max_pull_samples = int(max_pull_samples)
        self.inlet = None
        self.online = False
        self.samples_total = 0
        self.start_lsl = None
        self.last_sample_ts = None
        self.last_tick_lsl = None
        self.last_heartbeat_lsl = None
        self.recent = []
        self.warning_open = False
        self.dropout_open = False
        self.rate_invalid_open = False
        self.max_gap_seen = 0.0
        self.gaps_gt_250ms = 0

    def connect(self) -> bool:
        streams = resolve_byprop("name", self.stream_name, timeout=self.resolve_timeout_sec)
        if not streams:
            push_marker(self.outlet, self.logger, "EEG_WATCHDOG_NO_STREAM", phase="SETUP", note=self.stream_name)
            return False
        self.inlet = StreamInlet(streams[0], max_chunklen=self.max_pull_samples)
        self.online = True
        self.start_lsl = local_clock()
        self.last_tick_lsl = self.start_lsl
        self.last_heartbeat_lsl = self.start_lsl
        push_marker(self.outlet, self.logger, "EEG_WATCHDOG_ONLINE", phase="SETUP", note=self.stream_name)
        return True

    def tick(self, phase: str = "") -> None:
        if not self.online or self.inlet is None:
            return
        try:
            samples, timestamps = self.inlet.pull_chunk(timeout=0.0, max_samples=self.max_pull_samples)
        except Exception as exc:
            push_marker(self.outlet, self.logger, "EEG_WATCHDOG_PULL_ERROR", phase=phase, note=repr(exc))
            self.online = False
            return
        now = local_clock()
        if timestamps:
            for ts in timestamps:
                if self.last_sample_ts is not None:
                    gap = float(ts - self.last_sample_ts)
                    if gap > self.max_gap_seen:
                        self.max_gap_seen = gap
                    if gap > 0.25:
                        self.gaps_gt_250ms += 1
                        push_marker(self.outlet, self.logger, "EEG_GAP_GT_250MS", phase=phase, note=f"gap_sec={gap:.6f}")
                self.last_sample_ts = float(ts)
            self.samples_total += len(timestamps)
            self.recent.append((now, len(timestamps)))
            cutoff = now - self.rate_window_sec
            self.recent = [(t, n) for (t, n) in self.recent if t >= cutoff]
            if self.dropout_open:
                push_marker(self.outlet, self.logger, "EEG_DROPOUT_RECOVERED", phase=phase, note=f"samples_total={self.samples_total}")
                self.dropout_open = False
                self.warning_open = False
        if self.last_sample_ts is not None:
            silence = now - self.last_sample_ts
            if silence > self.warning_gap_sec and not self.warning_open:
                push_marker(self.outlet, self.logger, "EEG_GAP_WARNING", phase=phase, note=f"seconds_since_last_sample={silence:.3f}")
                self.warning_open = True
            if silence > self.invalid_gap_sec and not self.dropout_open:
                push_marker(self.outlet, self.logger, "EEG_DROPOUT_DETECTED", phase=phase, note=f"seconds_since_last_sample={silence:.3f}")
                self.dropout_open = True
        if self.last_heartbeat_lsl is not None and (now - self.last_heartbeat_lsl) >= self.heartbeat_sec:
            elapsed = max(1e-9, now - (self.start_lsl or now))
            eff_rate = self.samples_total / elapsed
            span = max(1e-9, self.recent[-1][0] - self.recent[0][0]) if len(self.recent) > 1 else 0.0
            recent_rate = (sum(n for _, n in self.recent) / span) if span > 0 else 0.0
            note = (
                f"samples_total={self.samples_total};effective_rate={eff_rate:.3f};"
                f"recent_rate={recent_rate:.3f};max_gap_seen={self.max_gap_seen:.6f};"
                f"gaps_gt_250ms={self.gaps_gt_250ms};dropout_open={self.dropout_open}"
            )
            push_marker(self.outlet, self.logger, "EEG_WATCHDOG_HEARTBEAT", phase=phase, note=note)
            if recent_rate > 0 and recent_rate < self.rate_warn_hz:
                push_marker(self.outlet, self.logger, "EEG_RATE_WARNING", phase=phase, note=note)
            if recent_rate > 0 and recent_rate < self.rate_invalid_hz and not self.rate_invalid_open:
                push_marker(self.outlet, self.logger, "EEG_RATE_INVALID", phase=phase, note=note)
                self.rate_invalid_open = True
            if recent_rate >= self.rate_warn_hz:
                self.rate_invalid_open = False
            self.last_heartbeat_lsl = now

    def final_note(self) -> str:
        now = local_clock()
        elapsed = max(1e-9, now - (self.start_lsl or now)) if self.start_lsl is not None else 0.0
        eff_rate = self.samples_total / elapsed if elapsed else 0.0
        return (
            f"samples_total={self.samples_total};elapsed={elapsed:.3f};effective_rate={eff_rate:.3f};"
            f"max_gap_seen={self.max_gap_seen:.6f};gaps_gt_250ms={self.gaps_gt_250ms};dropout_open={self.dropout_open}"
        )


def tick_eeg_watchdog(outlet: StreamOutlet, logger: EventLogger, phase: str = "") -> None:
    global ACTIVE_EEG_WATCHDOG
    if ACTIVE_EEG_WATCHDOG is not None:
        ACTIVE_EEG_WATCHDOG.tick(phase=phase)


@dataclass
class CueEvent:
    cue_index: int
    value: int
    start_sec: float
    end_sec: float


class EventLogger:
    def __init__(self, log_dir: Path, participant_id: str, session_id: str, run_label: str) -> None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_pid = sanitize_for_filename(participant_id or "P001")
        safe_sid = sanitize_for_filename(session_id or "S001")
        safe_run = sanitize_for_filename(run_label or "run")
        self.log_dir = log_dir
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.csv_path = self.log_dir / f"PRAYCG_v1_8_{safe_pid}_{safe_sid}_{safe_run}_{timestamp}_events.csv"
        self.json_path = self.log_dir / f"PRAYCG_v1_8_{safe_pid}_{safe_sid}_{safe_run}_{timestamp}_events.json"
        self.rows: List[Dict[str, Any]] = []
        self.csv_file = self.csv_path.open("w", newline="", encoding="utf-8")
        self.writer = csv.DictWriter(
            self.csv_file,
            fieldnames=["marker", "phase", "note", "lsl_time", "unix_time", "psychopy_time"],
        )
        self.writer.writeheader()

    def log(self, marker: str, phase: str = "", note: str = "", lsl_time_override: Optional[float] = None) -> None:
        row = {
            "marker": marker,
            "phase": phase,
            "note": note,
            "lsl_time": float(lsl_time_override) if lsl_time_override is not None else local_clock(),
            "unix_time": time.time(),
            "psychopy_time": core.getTime(),
        }
        self.rows.append(row)
        self.writer.writerow(row)
        self.csv_file.flush()

    def close(self) -> None:
        self.csv_file.flush()
        self.csv_file.close()
        self.json_path.write_text(json.dumps(self.rows, indent=2), encoding="utf-8")


def sanitize_for_filename(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_") or "NA"


def sanitize_marker_part(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_") or "NA"


def push_marker(outlet: StreamOutlet, logger: EventLogger, marker: str, phase: str = "", note: str = "") -> None:
    """Push one marker to LSL and mirror it to the local CSV/JSON log.

    The local log is useful, but the XDF stream is the authority for physiology alignment.
    Version 1.8 therefore timestamps the LSL sample explicitly with pylsl.local_clock()
    and requests pushthrough when the installed pylsl version supports it.
    """
    marker = sanitize_marker_part(marker)
    ts = local_clock()
    try:
        outlet.push_sample([marker], timestamp=ts, pushthrough=True)
    except TypeError:
        # Older pylsl builds may not expose pushthrough as a keyword.
        outlet.push_sample([marker], timestamp=ts)
    logger.log(marker, phase=phase, note=note, lsl_time_override=ts)
    print(f"MARKER {marker} | lsl_time={ts:.6f} | phase={phase} | note={note}")




def write_channel_map_csv(
    logger: EventLogger,
    rows: Sequence[Tuple[int, str, str]],
    *,
    map_label: str,
    confirmed: bool,
    confidence: str,
    notes: str = "",
) -> Path:
    out = logger.log_dir / f"{logger.csv_path.stem}_channel_map.csv"
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["openbci_channel", "electrode_location", "roi", "map_label", "confirmed", "confidence", "notes"],
        )
        writer.writeheader()
        for ch, electrode, roi in rows:
            writer.writerow({
                "openbci_channel": ch,
                "electrode_location": electrode,
                "roi": roi,
                "map_label": map_label,
                "confirmed": int(bool(confirmed)),
                "confidence": confidence,
                "notes": notes,
            })
    return out


def emit_channel_map_markers(
    outlet: StreamOutlet,
    logger: EventLogger,
    rows: Sequence[Tuple[int, str, str]],
    *,
    map_label: str,
    confirmed: bool,
    confidence: str,
    notes: str = "",
) -> None:
    """Emit parseable LSL markers documenting OpenBCI channel -> electrode mapping."""
    clean_label = sanitize_marker_part(map_label)
    clean_conf = sanitize_marker_part(confidence.upper())
    csv_path = write_channel_map_csv(logger, rows, map_label=map_label, confirmed=confirmed, confidence=confidence, notes=notes)

    push_marker(outlet, logger, "CHANNEL_MAP_START", phase="SETUP", note=str(csv_path))
    push_marker(outlet, logger, f"CHANNEL_MAP_LABEL_{clean_label}", phase="SETUP", note=map_label)
    push_marker(outlet, logger, f"CHANNEL_MAP_CONFIRMED_{'TRUE' if confirmed else 'FALSE'}", phase="SETUP", note=notes)
    push_marker(outlet, logger, f"CHANNEL_MAP_CONFIDENCE_{clean_conf}", phase="SETUP", note=confidence)
    if not confirmed or clean_conf in {"UNKNOWN", "UNCONFIRMED", "NONE"}:
        push_marker(outlet, logger, "CHANNEL_MAP_UNCONFIRMED_DO_NOT_USE_ROI", phase="SETUP", note=notes)
    for ch, electrode, roi in rows:
        push_marker(
            outlet,
            logger,
            f"CHANNEL_MAP_CH{int(ch):02d}_{sanitize_marker_part(electrode)}_ROI_{sanitize_marker_part(roi)}",
            phase="SETUP",
            note=f"channel={ch};electrode={electrode};roi={roi};map_label={map_label};confirmed={confirmed};confidence={confidence}",
        )
    push_marker(outlet, logger, "CHANNEL_MAP_END", phase="SETUP", note=str(csv_path))


def check_escape(outlet: StreamOutlet, logger: EventLogger, win: visual.Window, phase: str = "") -> None:
    if "escape" in event.getKeys(keyList=["escape"]):
        push_marker(outlet, logger, "EMERGENCY_KILL", phase=phase)
        logger.close()
        win.close()
        core.quit()


def parse_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    s = str(value).strip().lower()
    return s in {"1", "true", "yes", "y", "on"}


def parse_int(value: Any, default: int) -> int:
    try:
        return int(str(value).strip())
    except Exception:
        return default


def parse_float(value: Any, default: float) -> float:
    try:
        return float(str(value).strip())
    except Exception:
        return default


def clamp_float(value: float, low: float, high: float) -> float:
    return max(low, min(high, float(value)))


def resolve_stream_names(timeout: float = 1.0) -> List[str]:
    streams = resolve_byprop("type", "", timeout=timeout)
    names = []
    for stream in streams:
        try:
            names.append(stream.name())
        except Exception:
            pass
    # resolve_byprop('', '') can be backend-sensitive. Try broad common types if empty.
    if not names:
        for stream_type in ["EEG", "Markers", "HRV", "ECG", "Respiration", "RespirationBelt"]:
            for stream in resolve_byprop("type", stream_type, timeout=0.25):
                try:
                    names.append(stream.name())
                except Exception:
                    pass
    return sorted(set(names))


def load_cue_schedule(path: str) -> Tuple[List[CueEvent], Optional[int], Dict[str, Any]]:
    if not path or not Path(path).exists():
        return [], None, {}
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    cues = []
    for row in payload.get("cue_events", []):
        cues.append(
            CueEvent(
                cue_index=int(row["cue_index"]),
                value=int(row["value"]),
                start_sec=float(row["start_sec"]),
                end_sec=float(row["end_sec"]),
            )
        )
    expected = payload.get("expected_sum", None)
    expected_int = int(expected) if expected is not None and str(expected).strip() else None
    return cues, expected_int, payload


def show_text_and_wait(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    text: str,
    *,
    phase: str,
    marker_prefix: str,
    key_list: Sequence[str] = ("space", "return"),
) -> None:
    push_marker(outlet, logger, f"{marker_prefix}_START", phase=phase)
    stim = visual.TextStim(win, text=text, color="white", height=32, wrapWidth=1550, alignText="center")
    stim.draw()
    win.flip()
    event.clearEvents()
    while True:
        keys = event.getKeys(keyList=list(key_list) + ["escape"])
        if "escape" in keys:
            check_escape(outlet, logger, win, phase=phase)
        if any(k in keys for k in key_list):
            break
        tick_eeg_watchdog(outlet, logger, phase)
        core.wait(0.02)
    win.flip()
    push_marker(outlet, logger, f"{marker_prefix}_END", phase=phase)


def show_instruction_wait_then_stillness(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    text: str,
    *,
    phase: str,
    marker_prefix: str,
    stillness_duration: float,
    stillness_phase_name: Optional[str] = None,
    stillness_reason: str = "",
) -> None:
    """Show a proceed screen, then run stillness before the next analyzable block.

    v1.6R transition rule:
        report/input -> press SPACE to proceed -> stillness countdown -> clip/block starts.

    This prevents the final keypress from occurring immediately before the next video,
    which would contaminate the first seconds of the next physiology block with movement,
    posture correction, and hand/shoulder/jaw tension.
    """
    instructional_text = (
        text.rstrip()
        + "\n\nAfter you press SPACE, do not type or move."
        + "\nAn 8-10 second stillness countdown will run, then the next block starts automatically."
    )
    clean_phase = sanitize_marker_part(phase)
    push_marker(outlet, logger, "PROCEED_PROMPT_START", phase=phase, note=marker_prefix)
    push_marker(outlet, logger, f"PROCEED_PROMPT_{clean_phase}_START", phase=phase, note=marker_prefix)
    show_text_and_wait(
        win,
        outlet,
        logger,
        instructional_text,
        phase=phase,
        marker_prefix=marker_prefix,
    )
    push_marker(outlet, logger, f"PROCEED_PROMPT_{clean_phase}_END", phase=phase, note=marker_prefix)
    push_marker(outlet, logger, "PROCEED_PROMPT_END", phase=phase, note=marker_prefix)
    push_marker(outlet, logger, f"{clean_phase}_PROCEED_CONFIRMED_BEFORE_STILLNESS", phase=phase)
    return_to_stillness(
        win,
        outlet,
        logger,
        phase_name=stillness_phase_name or f"{sanitize_marker_part(phase)}_PRE_START_STILLNESS",
        duration=stillness_duration,
        reason=stillness_reason or f"after_{sanitize_marker_part(phase).lower()}_instruction_proceed_before_block_start",
    )


def wait_for_right_click(win: visual.Window, outlet: StreamOutlet, logger: EventLogger) -> None:
    """Hold experiment while StasisMarkers is alive so LabRecorder can capture it.

    This fixes the main 1.6J/1.6L failure mode: starting LabRecorder before the marker
    outlet existed. Do not start LabRecorder before this screen. While this screen is
    visible, the script emits repeated LSL_PREFLIGHT_PING_* markers once per second.
    """
    text = (
        "LSL Marker Stream Is Now Online.\n\n"
        "DO THIS NOW, IN THIS ORDER:\n"
        "1. Open LabRecorder if it is not already open.\n"
        "2. Click UPDATE.\n"
        "3. Confirm these streams are visible and checked:\n"
        "   - StasisMarkers\n"
        "   - obci_eeg1\n"
        "   - PolarHRV if used\n"
        "   - VernierRespirationBelt if used\n"
        "4. Click START in LabRecorder.\n\n"
        "This screen will keep sending LSL_PREFLIGHT_PING markers.\n"
        "This window is intentionally NOT fullscreen so you can Alt-Tab or click LabRecorder.\n"
        "If StasisMarkers is not visible in LabRecorder, stop now and fix it.\n\n"
        "LEFT-CLICK once to focus this screen.\n"
        "RIGHT-CLICK only after LabRecorder is recording StasisMarkers."
    )
    push_marker(outlet, logger, "LSL_PREFLIGHT_HOLD_START", phase="SETUP", note="Start LabRecorder during this hold, not before script launch.")
    msg = visual.TextStim(win, text=text, color="white", height=32, wrapWidth=1600, alignText="center")
    msg.draw()
    win.flip()
    mouse = event.Mouse(win=win)
    mouse.clickReset()
    hold_clock = core.Clock()
    next_ping = 0.0
    ping_n = 0
    while True:
        now = hold_clock.getTime()
        if now >= next_ping:
            ping_n += 1
            push_marker(outlet, logger, f"LSL_PREFLIGHT_PING_{ping_n:03d}", phase="SETUP", note="If LabRecorder records StasisMarkers, this ping should appear in the XDF.")
            next_ping = now + 1.0
        buttons = mouse.getPressed()
        if buttons[2]:
            break
        check_escape(outlet, logger, win, phase="SETUP")
        tick_eeg_watchdog(outlet, logger, "SETUP")
        msg.draw()
        win.flip()
        core.wait(0.03)
    push_marker(outlet, logger, "LSL_PREFLIGHT_HOLD_END", phase="SETUP", note=f"pings_sent={ping_n}")
    win.flip()
    core.wait(0.5)

def return_to_stillness(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    duration: float,
    reason: str = "",
) -> None:
    """Insert a non-analysis stillness reset after typing/report movement.

    This block is deliberately bracketed with broad and phase-specific markers. Analysis
    scripts can hard-exclude the report/sum windows and use this reset as a settling buffer
    before the next analyzable physiology block.
    """
    duration = clamp_float(duration, MIN_STILLNESS_RESET_SEC, MAX_STILLNESS_RESET_SEC)
    note = f"duration_sec={duration:.3f};reason={reason}"
    push_marker(outlet, logger, "RETURN_TO_STILLNESS_START", phase=phase_name, note=note)
    push_marker(outlet, logger, f"RETURN_TO_STILLNESS_{phase_name}_START", phase=phase_name, note=note)

    reset_clock = core.Clock()
    stim = visual.TextStim(win, text="", color="white", height=34, wrapWidth=1500, alignText="center")
    while reset_clock.getTime() < duration:
        remaining = max(0.0, duration - reset_clock.getTime())
        stim.text = (
            "Return to stillness.\n\n"
            "Sit back in the chair. Put hands in lap.\n"
            "Relax jaw, shoulders, neck, forehead, and tongue.\n"
            "Eyes on the cross. Breathe normally.\n\n"
            f"Stillness reset: {remaining:0.1f} seconds"
        )
        stim.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
        tick_eeg_watchdog(outlet, logger, phase_name)
        core.wait(0.02)
    win.flip()
    push_marker(outlet, logger, f"RETURN_TO_STILLNESS_{phase_name}_END", phase=phase_name, note=note)
    push_marker(outlet, logger, "RETURN_TO_STILLNESS_END", phase=phase_name, note=note)


def run_baseline(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    fixation: visual.TextStim,
    *,
    duration: float,
    phase_name: str,
) -> None:
    push_marker(outlet, logger, f"{phase_name}_START", phase=phase_name)
    clock = core.Clock()
    while clock.getTime() < duration:
        fixation.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
        tick_eeg_watchdog(outlet, logger, phase_name)
    push_marker(outlet, logger, f"{phase_name}_END", phase=phase_name)


def _get_movie_duration(mov: Any) -> Optional[float]:
    for attr in ("duration", "_duration"):
        try:
            val = getattr(mov, attr)
            if val is not None and float(val) > 0:
                return float(val)
        except Exception:
            pass
    return None


def play_video(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    video_path: str,
    *,
    phase_name: str,
    cue_events: Sequence[CueEvent] = (),
    emit_cue_markers: bool = True,
    movie_draw_size: Optional[Tuple[int, int]] = None,
) -> None:
    path = Path(video_path).expanduser()
    if not path.exists():
        push_marker(outlet, logger, f"ERROR_MISSING_{phase_name}_MEDIA", phase=phase_name, note=str(path))
        raise FileNotFoundError(path)

    push_marker(outlet, logger, f"{phase_name}_LOAD_OK", phase=phase_name, note=str(path))
    mov_kwargs = {"flipVert": False, "flipHoriz": False, "loop": False}
    mov_kwargs["size"] = tuple(movie_draw_size) if movie_draw_size is not None else (1920, 1080)
    mov = visual.MovieStim(win, str(path), **mov_kwargs)
    if movie_draw_size is not None:
        push_marker(outlet, logger, f"{phase_name}_MOVIE_DRAW_SIZE_{movie_draw_size[0]}x{movie_draw_size[1]}", phase=phase_name)
    duration = _get_movie_duration(mov)
    timeout_limit = (duration + 0.35) if duration else 9999.0

    # First flip after loading gives a clean visual reset before the start marker.
    win.flip()
    core.wait(0.05)

    push_marker(outlet, logger, f"{phase_name}_START", phase=phase_name)
    try:
        mov.play()
    except Exception:
        pass

    play_clock = core.Clock()
    cue_start_sent = set()
    cue_end_sent = set()

    while mov.status != FINISHED:
        t = play_clock.getTime()
        if emit_cue_markers:
            for cue in cue_events:
                if cue.cue_index not in cue_start_sent and t >= cue.start_sec:
                    push_marker(
                        outlet,
                        logger,
                        f"{phase_name}_CUE_{cue.cue_index:03d}_VALUE_{cue.value}_START",
                        phase=phase_name,
                        note=f"t={cue.start_sec:.3f}",
                    )
                    cue_start_sent.add(cue.cue_index)
                if cue.cue_index not in cue_end_sent and t >= cue.end_sec:
                    push_marker(
                        outlet,
                        logger,
                        f"{phase_name}_CUE_{cue.cue_index:03d}_VALUE_{cue.value}_END",
                        phase=phase_name,
                        note=f"t={cue.end_sec:.3f}",
                    )
                    cue_end_sent.add(cue.cue_index)
        mov.draw()
        win.flip()
        check_escape(outlet, logger, win, phase=phase_name)
        tick_eeg_watchdog(outlet, logger, phase_name)
        if play_clock.getTime() >= timeout_limit:
            push_marker(outlet, logger, f"{phase_name}_TIMEOUT_BREAK", phase=phase_name)
            break
    try:
        mov.stop()
    except Exception:
        pass
    push_marker(outlet, logger, f"{phase_name}_END", phase=phase_name)
    win.flip()


def collect_numeric_response(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    expected_sum: Optional[int],
    reward_text: str = "",
) -> Tuple[Optional[int], Optional[bool]]:
    push_marker(outlet, logger, "SUM_INPUT_START", phase=phase_name, note=phase_name)
    push_marker(outlet, logger, f"SUM_INPUT_{phase_name}_START", phase=phase_name)
    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_START", phase=phase_name)
    response = ""
    prompt = visual.TextStim(win, text="", color="white", height=38, wrapWidth=1500, alignText="center")
    event.clearEvents()

    while True:
        prompt.text = (
            "Contextual Override Sum\n\n"
            "Type the running sum of all numbers you saw.\n"
            "Press ENTER when done. Backspace edits.\n\n"
            f"Current answer: {response if response else '_'}"
        )
        prompt.draw()
        win.flip()
        tick_eeg_watchdog(outlet, logger, phase_name)
        keys = event.getKeys(keyList=list("0123456789") + ["backspace", "return", "enter", "escape"])
        for k in keys:
            if k == "escape":
                check_escape(outlet, logger, win, phase=phase_name)
            elif k == "backspace":
                response = response[:-1]
            elif k in ("return", "enter"):
                if response.strip():
                    try:
                        numeric = int(response)
                    except ValueError:
                        numeric = None
                    correct = (numeric == expected_sum) if expected_sum is not None and numeric is not None else None
                    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_{numeric if numeric is not None else 'INVALID'}", phase=phase_name)
                    if expected_sum is not None:
                        push_marker(outlet, logger, f"RESPONSE_{phase_name}_EXPECTED_SUM_{expected_sum}", phase=phase_name)
                    if correct is not None:
                        push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_CORRECT_{1 if correct else 0}", phase=phase_name)
                    push_marker(outlet, logger, f"RESPONSE_{phase_name}_SUM_END", phase=phase_name)
                    push_marker(outlet, logger, f"SUM_INPUT_{phase_name}_END", phase=phase_name)
                    push_marker(outlet, logger, "SUM_INPUT_END", phase=phase_name, note=phase_name)

                    if correct and reward_text.strip():
                        msg = visual.TextStim(win, text=reward_text, color="white", height=38, wrapWidth=1500, alignText="center")
                        msg.draw()
                        win.flip()
                        push_marker(outlet, logger, f"REWARD_DISPLAYED_{phase_name}", phase=phase_name, note=reward_text.strip())
                        core.wait(2.0)
                    else:
                        msg_text = "Response recorded."
                        if correct is False:
                            msg_text = "Response recorded."
                        msg = visual.TextStim(win, text=msg_text, color="white", height=38, wrapWidth=1500, alignText="center")
                        msg.draw()
                        win.flip()
                        core.wait(1.0)
                    return numeric, correct
            elif k.isdigit():
                # Prevent runaway accidental input.
                if len(response) < 8:
                    response += k
        core.wait(0.02)


def collect_rating(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    item: str,
) -> int:
    text = (
        f"{item}\n\n"
        "Rate 0-9.\n"
        "0 = none / not at all\n"
        "9 = very high / very strong\n\n"
        "Press one number key."
    )
    stim = visual.TextStim(win, text=text, color="white", height=38, wrapWidth=1500, alignText="center")
    stim.draw()
    win.flip()
    event.clearEvents()
    while True:
        tick_eeg_watchdog(outlet, logger, phase_name)
        keys = event.getKeys(keyList=list("0123456789") + ["escape"])
        if "escape" in keys:
            check_escape(outlet, logger, win, phase=phase_name)
        for k in keys:
            if k.isdigit():
                rating = int(k)
                push_marker(outlet, logger, f"RATING_{phase_name}_{item}_{rating}", phase=phase_name)
                core.wait(0.15)
                return rating
        core.wait(0.02)


def collect_phase_ratings(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    items: Sequence[str] = STANDARD_RATING_ITEMS,
) -> Dict[str, int]:
    push_marker(outlet, logger, "REPORT_INPUT_START", phase=phase_name, note=phase_name)
    push_marker(outlet, logger, f"REPORT_INPUT_{phase_name}_START", phase=phase_name)
    push_marker(outlet, logger, f"RATINGS_{phase_name}_START", phase=phase_name)
    results: Dict[str, int] = {}
    for item in items:
        results[item] = collect_rating(win, outlet, logger, phase_name=phase_name, item=item)
    result_note = json.dumps(results, sort_keys=True)
    push_marker(outlet, logger, f"RATINGS_{phase_name}_END", phase=phase_name, note=result_note)
    push_marker(outlet, logger, f"REPORT_INPUT_{phase_name}_END", phase=phase_name, note=result_note)
    push_marker(outlet, logger, "REPORT_INPUT_END", phase=phase_name, note=result_note)
    return results



def _extract_video_size_from_payload(cue_payload: Dict[str, Any]) -> Tuple[int, int]:
    """Best-effort natural stimulus size from the cue schedule/manifest payload."""
    for key in ("video", "video_props"):
        video = cue_payload.get(key, {}) if isinstance(cue_payload, dict) else {}
        try:
            w = int(video.get("width", 0))
            h = int(video.get("height", 0))
            if w > 0 and h > 0:
                return w, h
        except Exception:
            pass
    return 1920, 1080


def calculate_movie_draw_size(win: visual.Window, cfg: Dict[str, Any], natural_size: Tuple[int, int]) -> Tuple[int, int]:
    """Return a movie draw size in PsychoPy pix units.

    This is a presentation-layer fix for high-DPI laptops. It does not alter the .mp4 or cue schedule;
    it draws the entire movie slightly inside the screen boundary so baked-in upper-right cues are less
    vulnerable to edge/crop artifacts.
    """
    nat_w, nat_h = max(1, int(natural_size[0])), max(1, int(natural_size[1]))
    mode = str(cfg.get("movie_display_mode", "safe_fit")).strip().lower()
    custom_w = int(cfg.get("movie_custom_width_px", 0) or 0)
    custom_h = int(cfg.get("movie_custom_height_px", 0) or 0)
    if mode in {"custom", "custom_size"} and custom_w > 0 and custom_h > 0:
        return custom_w, custom_h
    if mode in {"native", "native_size"}:
        return nat_w, nat_h
    try:
        win_w, win_h = int(win.size[0]), int(win.size[1])
    except Exception:
        win_w, win_h = 1920, 1080
    fraction = clamp_float(float(cfg.get("movie_safe_fit_fraction", DEFAULT_MOVIE_SAFE_FIT_FRACTION)), 0.50, 1.00)
    if mode in {"fit", "fit_screen", "fullscreen_fit"}:
        fraction = 1.00
    scale = min((win_w * fraction) / nat_w, (win_h * fraction) / nat_h)
    return max(1, int(round(nat_w * scale))), max(1, int(round(nat_h * scale)))


def collect_text_response(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    phase_name: str,
    prompt_text: str,
    marker_prefix: str,
    max_chars: int = 900,
) -> str:
    """Collect short typed free-text notes inside PsychoPy."""
    push_marker(outlet, logger, f"{marker_prefix}_START", phase=phase_name)
    response = ""
    stim = visual.TextStim(win, text="", color="white", height=30, wrapWidth=1550, alignText="left")
    event.clearEvents()
    key_map = {
        "space": " ", "period": ".", "comma": ",", "minus": "-", "slash": "/",
        "semicolon": ";", "apostrophe": "'", "bracketleft": "[", "bracketright": "]",
        "backslash": "\\", "equal": "=", "quoteleft": "`", "grave": "`",
    }
    while True:
        visible = response[-700:]
        stim.text = (
            f"{prompt_text}\n\n"
            "Type a short response. Press ENTER when finished. Backspace edits.\n"
            "If none, type NONE.\n\n"
            f"Response:\n{visible}_"
        )
        stim.draw()
        win.flip()
        tick_eeg_watchdog(outlet, logger, phase_name)
        keys = event.getKeys()
        for k in keys:
            if k == "escape":
                check_escape(outlet, logger, win, phase=phase_name)
            elif k in ("return", "enter"):
                clean = response.strip()
                push_marker(outlet, logger, f"{marker_prefix}_END", phase=phase_name, note=clean)
                return clean
            elif k == "backspace":
                response = response[:-1]
            elif len(response) < max_chars:
                if k in key_map:
                    response += key_map[k]
                elif len(k) == 1 and k.isprintable():
                    response += k
                elif k.startswith("num_") and len(k) == 5 and k[-1].isdigit():
                    response += k[-1]
        core.wait(0.02)


def collect_final_master_report(
    win: visual.Window,
    outlet: StreamOutlet,
    logger: EventLogger,
    *,
    items: Sequence[str] = STANDARD_RATING_ITEMS,
) -> Dict[str, Any]:
    """Final cross-condition subjective report after BASELINE_2_REFLECTION."""
    phase = "FINAL_MASTER_REPORT"
    push_marker(outlet, logger, "FINAL_MASTER_REPORT_START", phase=phase)
    intro = (
        "Final Master Subjective Report\n\n"
        "You have now completed Control, Target, and Contextual Override.\n"
        "Rate each video again from your final, comparative perspective.\n"
        "Then type brief frozen notes about what, if anything, felt meaningful.\n\n"
        "Press SPACE to begin."
    )
    show_text_and_wait(win, outlet, logger, intro, phase=phase, marker_prefix="FINAL_MASTER_REPORT_INTRO")
    branches = [
        ("CONTROL", "phase-scrambled / static Control video"),
        ("TARGET", "intact Target video"),
        ("OVERRIDE", "Contextual Override video"),
    ]
    results: Dict[str, Any] = {"ratings": {}, "frozen_notes": {}}
    for branch, branch_label in branches:
        branch_phase = f"FINAL_MASTER_REPORT_{branch}"
        push_marker(outlet, logger, f"{branch_phase}_START", phase=branch_phase, note=branch_label)
        branch_intro = (
            f"Final ratings for the {branch_label}.\n\n"
            "Use the same 0-9 scale as before.\n\n"
            "Press SPACE to continue."
        )
        show_text_and_wait(win, outlet, logger, branch_intro, phase=branch_phase, marker_prefix=f"{branch_phase}_INSTRUCTION")
        results["ratings"][branch] = collect_phase_ratings(win, outlet, logger, phase_name=branch_phase, items=items)
        prompt = (
            f"What specific portions of the {branch_label} did you find meaningful, if any?\n"
            "Give a short typed explanation. Include approximate moments, scenes, images, sounds, or thoughts if remembered."
        )
        results["frozen_notes"][branch] = collect_text_response(
            win,
            outlet,
            logger,
            phase_name=branch_phase,
            prompt_text=prompt,
            marker_prefix=f"FINAL_FROZEN_NOTE_{branch}",
        )
        push_marker(outlet, logger, f"{branch_phase}_END", phase=branch_phase)
    out_path = logger.log_dir / f"{logger.csv_path.stem}_final_master_subjective_report.json"
    out_path.write_text(json.dumps(results, indent=2, sort_keys=True), encoding="utf-8")
    push_marker(outlet, logger, "FINAL_MASTER_REPORT_SAVED", phase=phase, note=str(out_path))
    push_marker(outlet, logger, "FINAL_MASTER_REPORT_END", phase=phase, note=json.dumps(results, sort_keys=True))
    return results


def file_sha256(path: str, block_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with Path(path).expanduser().open("rb") as f:
        for block in iter(lambda: f.read(block_size), b""):
            h.update(block)
    return h.hexdigest()


def first_existing_default(patterns: Sequence[str]) -> str:
    bases = [Path.cwd(), Path(__file__).resolve().parent, Path(__file__).resolve().parent.parent]
    seen = set()
    for base in bases:
        if base in seen:
            continue
        seen.add(base)
        for pattern in patterns:
            hits = sorted(base.glob(pattern))
            if hits:
                return str(hits[0])
    return ""


def _validate_media_selection_dict(cfg: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    for key, label in [
        ("control_video", "Control video"),
        ("target_video", "Target video"),
        ("override_video", "Contextual Override video"),
    ]:
        val = str(cfg.get(key, "")).strip()
        if not val:
            errors.append(f"{label} is required.")
        elif not Path(val).expanduser().exists():
            errors.append(f"{label} does not exist: {val}")
        elif Path(val).suffix.lower() not in {".mp4", ".mov", ".m4v", ".avi", ".mkv"}:
            errors.append(f"{label} is not a recognized video file: {val}")

    cue_path = str(cfg.get("cue_schedule_json", "")).strip()
    if not cue_path:
        errors.append("Cue schedule JSON is required.")
    elif not Path(cue_path).expanduser().exists():
        errors.append(f"Cue schedule JSON does not exist: {cue_path}")
    elif Path(cue_path).suffix.lower() != ".json":
        errors.append(f"Cue schedule must be a .json file: {cue_path}")
    else:
        try:
            cues, expected, payload = load_cue_schedule(cue_path)
            if not cues:
                errors.append("Cue schedule JSON loaded, but no cue_events were found.")
            if expected is None and not str(cfg.get("expected_sum_manual", "")).strip():
                errors.append("Cue schedule JSON has no expected_sum; enter expected sum manually or regenerate the cue schedule.")
        except Exception as exc:
            errors.append(f"Cue schedule JSON could not be parsed: {exc}")
    return errors


def collect_gui_config_psychopy_fallback() -> Dict[str, Any]:
    """Fallback config dialog used only if Tkinter browse UI is unavailable."""
    dlg = gui.Dlg(title="PRAYCG1.8 Pre-Flight Fallback")
    dlg.addText("Tkinter browse UI was unavailable. Paste full file paths manually.")
    dlg.addText("Experiment identity")
    dlg.addField("Participant ID:", "P001")
    dlg.addField("Session ID:", "S001")
    dlg.addField("Run label:", "run001")
    dlg.addText("Media files")
    dlg.addField("Control video path:", first_existing_default(["stimulus_control*.mp4", "*control*.mp4"]))
    dlg.addField("Target video path:", first_existing_default(["stimulus_target*.mp4", "*target*.mp4"]))
    dlg.addField("Override video path:", first_existing_default(["stimulus_override*.mp4", "*override*.mp4"]))
    dlg.addField("Cue schedule JSON:", first_existing_default(["cue_schedule*.json", "*cue*.json"]))
    dlg.addField("Expected sum override (blank = load from schedule):", "")
    dlg.addText("Timing")
    dlg.addField("Baseline seconds:", "120")
    dlg.addField("Washout seconds:", "120")
    dlg.addField("Stillness reset seconds after pressing proceed, before next block (5-10):", "8")
    dlg.addField("Enable final reflection baseline/report True/False:", "True")
    dlg.addField("Final reflection baseline seconds:", "120")
    dlg.addField("Movie display mode native/safe_fit/fit/custom:", "safe_fit")
    dlg.addField("Movie safe-fit fraction 0.50-1.00:", "0.92")
    dlg.addField("Custom movie width px (0 = unused):", "0")
    dlg.addField("Custom movie height px (0 = unused):", "0")
    dlg.addText("EEG channel map")
    dlg.addField("Use standard PRAYCG16 fixed channel map True/False:", "True")
    dlg.addField("Channel map confirmed True/False:", "False")
    dlg.addField("Channel map confidence LOCKED/PROBABLE/UNKNOWN:", "UNKNOWN")
    dlg.addField("Channel map label:", "PRAYCG16_FIXED_ORDER_v1")
    dlg.addField("Channel map notes:", "Set confirmed=True only after wire-to-electrode map is photographed or physically traced.")
    dlg.addText("Display and logging")
    dlg.addField("Fullscreen True/False:", "True")
    dlg.addField("Screen index:", "0")
    dlg.addField("Log directory:", "praycg_run_logs")
    dlg.addField("Reward text if correct (blank = no reward):", "Correct. Response logged.")
    dlg.show()
    if not dlg.OK:
        core.quit()
    vals = dlg.data
    cfg = {
        "participant_id": vals[0],
        "session_id": vals[1],
        "run_label": vals[2],
        "control_video": vals[3],
        "target_video": vals[4],
        "override_video": vals[5],
        "cue_schedule_json": vals[6],
        "expected_sum_manual": vals[7],
        "baseline_seconds": parse_float(vals[8], 120.0),
        "washout_seconds": parse_float(vals[9], 120.0),
        "stillness_reset_seconds": clamp_float(parse_float(vals[10], DEFAULT_STILLNESS_RESET_SEC), MIN_STILLNESS_RESET_SEC, MAX_STILLNESS_RESET_SEC),
        "enable_final_reflection_baseline": parse_bool(vals[11]),
        "final_reflection_baseline_seconds": parse_float(vals[12], DEFAULT_FINAL_REFLECTION_BASELINE_SEC),
        "movie_display_mode": str(vals[13]).strip().lower() or "safe_fit",
        "movie_safe_fit_fraction": clamp_float(parse_float(vals[14], DEFAULT_MOVIE_SAFE_FIT_FRACTION), 0.50, 1.00),
        "movie_custom_width_px": parse_int(vals[15], 0),
        "movie_custom_height_px": parse_int(vals[16], 0),
        "use_standard_channel_map": parse_bool(vals[17]),
        "channel_map_confirmed": parse_bool(vals[18]),
        "channel_map_confidence": str(vals[19]).strip().upper() or "UNKNOWN",
        "channel_map_label": str(vals[20]).strip() or "PRAYCG16_FIXED_ORDER_v1",
        "channel_map_notes": str(vals[21]).strip(),
        "fullscreen": parse_bool(vals[22]),
        "screen_index": parse_int(vals[23], 0),
        "log_dir": vals[24],
        "reward_text": vals[25],
        "config_gui_mode": "psychopy_fallback_no_browse_buttons_v1_8",
    }
    errors = _validate_media_selection_dict(cfg)
    if errors:
        raise RuntimeError("Preflight validation failed:\n" + "\n".join(errors))
    return cfg


def collect_gui_config() -> Dict[str, Any]:
    """Collect PRAYCG run configuration using a compact Tkinter GUI.

    v1.8 is a layout patch over v1.6T. It preserves browse-file media selection,
    EEG watchdog settings, cue-schedule hard-stop behavior, and the settle-after-proceed
    acquisition logic, but reorganizes the preflight GUI into tabs with a fixed bottom
    launch bar so the Run button stays visible on smaller laptop displays.
    """
    try:
        import tkinter as tk
        from tkinter import filedialog, messagebox, ttk
    except Exception:
        return collect_gui_config_psychopy_fallback()

    root = tk.Tk()
    root.title("PRAYCG1.8 Compact Pre-Flight")

    # Fit the GUI to the current laptop display instead of assuming a tall monitor.
    screen_w = max(800, int(root.winfo_screenwidth()))
    screen_h = max(600, int(root.winfo_screenheight()))
    win_w = min(940, max(760, screen_w - 80))
    win_h = min(660, max(520, screen_h - 120))
    x = max(0, int((screen_w - win_w) / 2))
    y = max(0, int((screen_h - win_h) / 3))
    root.geometry(f"{win_w}x{win_h}+{x}+{y}")
    root.minsize(740, 500)
    root.columnconfigure(0, weight=1)
    root.rowconfigure(1, weight=1)

    result: Dict[str, Any] = {}

    defaults = {
        "participant_id": "P001",
        "session_id": "S001",
        "run_label": "run001",
        "control_video": first_existing_default(["stimulus_control*.mp4", "*control*.mp4"]),
        "target_video": first_existing_default(["stimulus_target*.mp4", "*target*.mp4"]),
        "override_video": first_existing_default(["stimulus_override*.mp4", "*override*.mp4"]),
        "cue_schedule_json": first_existing_default(["cue_schedule*.json", "*cue*.json"]),
        "expected_sum_manual": "",
        "baseline_seconds": "120",
        "washout_seconds": "120",
        "stillness_reset_seconds": "8",
        "enable_final_reflection_baseline": True,
        "final_reflection_baseline_seconds": "120",
        "movie_display_mode": "safe_fit",
        "movie_safe_fit_fraction": "0.92",
        "movie_custom_width_px": "0",
        "movie_custom_height_px": "0",
        "use_standard_channel_map": True,
        "channel_map_confirmed": False,
        "channel_map_confidence": "UNKNOWN",
        "channel_map_label": "PRAYCG16_FIXED_ORDER_v1",
        "channel_map_notes": "Set confirmed=True only after wire-to-electrode map is photographed or physically traced.",
        "fullscreen": True,
        "screen_index": "0",
        "log_dir": "praycg_run_logs",
        "reward_text": "Correct. Response logged.",
        "enable_eeg_watchdog": True,
        "eeg_watchdog_stream_name": "obci_eeg1",
        "eeg_watchdog_expected_rate_hz": "125",
        "eeg_watchdog_warning_gap_sec": "1.0",
        "eeg_watchdog_invalid_gap_sec": "3.0",
        "eeg_watchdog_rate_warn_hz": "115",
        "eeg_watchdog_rate_invalid_hz": "100",
    }

    vars_s: Dict[str, Any] = {}
    for key, val in defaults.items():
        if isinstance(val, bool):
            vars_s[key] = tk.BooleanVar(value=val)
        else:
            vars_s[key] = tk.StringVar(value=str(val))

    header_frame = ttk.Frame(root, padding=(12, 10, 12, 4))
    header_frame.grid(row=0, column=0, sticky="ew")
    header_frame.columnconfigure(0, weight=1)
    ttk.Label(
        header_frame,
        text="PRAYCG1.8 Runner — final reflection baseline + display safe-fit",
        font=("Arial", 13, "bold"),
    ).grid(row=0, column=0, sticky="w")
    ttk.Label(
        header_frame,
        text="Adds final reflection baseline/report and safe-fit video sizing for high-DPI laptop displays.",
        foreground="#333333",
    ).grid(row=1, column=0, sticky="w", pady=(2, 0))

    notebook = ttk.Notebook(root)
    notebook.grid(row=1, column=0, sticky="nsew", padx=12, pady=(2, 4))

    def make_scroll_tab(title: str):
        outer = ttk.Frame(notebook)
        notebook.add(outer, text=title)
        outer.columnconfigure(0, weight=1)
        outer.rowconfigure(0, weight=1)
        canvas = tk.Canvas(outer, highlightthickness=0, borderwidth=0)
        vbar = ttk.Scrollbar(outer, orient="vertical", command=canvas.yview)
        inner = ttk.Frame(canvas, padding=(10, 10, 10, 12))
        window_id = canvas.create_window((0, 0), window=inner, anchor="nw")
        canvas.configure(yscrollcommand=vbar.set)
        canvas.grid(row=0, column=0, sticky="nsew")
        vbar.grid(row=0, column=1, sticky="ns")
        inner.columnconfigure(1, weight=1)

        def _on_frame_configure(_event=None):
            canvas.configure(scrollregion=canvas.bbox("all"))

        def _on_canvas_configure(event):
            canvas.itemconfigure(window_id, width=event.width)

        def _on_mousewheel(event):
            # Windows/macOS/Linux wheel normalization.
            delta = 0
            if getattr(event, "num", None) == 4:
                delta = -1
            elif getattr(event, "num", None) == 5:
                delta = 1
            elif getattr(event, "delta", 0):
                delta = -int(event.delta / 120)
            canvas.yview_scroll(delta, "units")

        inner.bind("<Configure>", _on_frame_configure)
        canvas.bind("<Configure>", _on_canvas_configure)
        canvas.bind_all("<MouseWheel>", _on_mousewheel)
        canvas.bind_all("<Button-4>", _on_mousewheel)
        canvas.bind_all("<Button-5>", _on_mousewheel)
        return inner

    tab_run = make_scroll_tab("Run")
    tab_media = make_scroll_tab("Media")
    tab_eeg = make_scroll_tab("EEG / Display")
    tab_watch = make_scroll_tab("Watchdog")

    def section(parent, row_ref, title: str) -> int:
        row = row_ref
        ttk.Label(parent, text=title, font=("Arial", 10, "bold")).grid(row=row, column=0, columnspan=4, sticky="w", pady=(8, 3))
        return row + 1

    def add_entry(parent, row_ref, label: str, key: str, width: int = 28) -> int:
        row = row_ref
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(parent, textvariable=vars_s[key], width=width).grid(row=row, column=1, columnspan=3, sticky="ew", pady=3)
        return row + 1

    def add_bool(parent, row_ref, label: str, key: str) -> int:
        row = row_ref
        ttk.Checkbutton(parent, text=label, variable=vars_s[key]).grid(row=row, column=0, columnspan=4, sticky="w", pady=3)
        return row + 1

    def browse_file(key: str, title: str, filetypes: Sequence[Tuple[str, str]]) -> None:
        current_raw = str(vars_s[key].get()).strip()
        current = Path(current_raw).expanduser() if current_raw else Path.cwd()
        initialdir = str(current.parent) if current_raw and current.parent.exists() else str(Path.cwd())
        chosen = filedialog.askopenfilename(title=title, initialdir=initialdir, filetypes=list(filetypes))
        if chosen:
            vars_s[key].set(chosen)

    def add_file_row(parent, row_ref, label: str, key: str, title: str, filetypes: Sequence[Tuple[str, str]]) -> int:
        row = row_ref
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", padx=(0, 8), pady=4)
        ttk.Entry(parent, textvariable=vars_s[key]).grid(row=row, column=1, sticky="ew", pady=4)
        ttk.Button(parent, text="Browse", command=lambda: browse_file(key, title, filetypes)).grid(row=row, column=2, sticky="ew", padx=(8, 0), pady=4)
        ttk.Button(parent, text="Clear", command=lambda: vars_s[key].set("")).grid(row=row, column=3, sticky="ew", padx=(6, 0), pady=4)
        return row + 1

    # Run tab
    r = 0
    r = section(tab_run, r, "Experiment identity")
    r = add_entry(tab_run, r, "Participant ID", "participant_id")
    r = add_entry(tab_run, r, "Session ID", "session_id")
    r = add_entry(tab_run, r, "Run label", "run_label")
    r = section(tab_run, r, "Timing")
    r = add_entry(tab_run, r, "Baseline seconds", "baseline_seconds")
    r = add_entry(tab_run, r, "Washout seconds", "washout_seconds")
    r = add_entry(tab_run, r, "Stillness reset seconds after SPACE", "stillness_reset_seconds")
    r = add_bool(tab_run, r, "Enable final reflection baseline/report", "enable_final_reflection_baseline")
    r = add_entry(tab_run, r, "Final reflection baseline seconds", "final_reflection_baseline_seconds")
    r = section(tab_run, r, "Logging")
    r = add_entry(tab_run, r, "Log directory", "log_dir")
    r = add_entry(tab_run, r, "Reward text if sum correct", "reward_text")

    # Media tab
    r = 0
    r = section(tab_media, r, "Required media files")
    video_types = (("Video files", "*.mp4 *.mov *.m4v *.avi *.mkv"), ("All files", "*.*"))
    json_types = (("JSON files", "*.json"), ("All files", "*.*"))
    r = add_file_row(tab_media, r, "Control video", "control_video", "Choose phase-scrambled Control video", video_types)
    r = add_file_row(tab_media, r, "Target video", "target_video", "Choose cue-embedded Target video", video_types)
    r = add_file_row(tab_media, r, "Override video", "override_video", "Choose cue-embedded Contextual Override video", video_types)
    r = add_file_row(tab_media, r, "Cue schedule JSON", "cue_schedule_json", "Choose cue schedule JSON", json_types)
    r = add_entry(tab_media, r, "Expected sum override", "expected_sum_manual")
    ttk.Label(tab_media, text="Leave expected sum blank unless the JSON lacks expected_sum.", foreground="#555555").grid(row=r, column=0, columnspan=4, sticky="w", pady=(2, 8))

    # EEG / Display tab
    r = 0
    r = section(tab_eeg, r, "EEG channel map")
    r = add_bool(tab_eeg, r, "Use standard PRAYCG16 fixed channel map", "use_standard_channel_map")
    r = add_bool(tab_eeg, r, "Channel map physically confirmed / photographed", "channel_map_confirmed")
    r = add_entry(tab_eeg, r, "Channel map confidence", "channel_map_confidence")
    r = add_entry(tab_eeg, r, "Channel map label", "channel_map_label")
    r = add_entry(tab_eeg, r, "Channel map notes", "channel_map_notes")
    r = section(tab_eeg, r, "Display")
    r = add_bool(tab_eeg, r, "Fullscreen experiment window", "fullscreen")
    r = add_entry(tab_eeg, r, "Screen index", "screen_index")
    r = add_entry(tab_eeg, r, "Movie display mode", "movie_display_mode")
    r = add_entry(tab_eeg, r, "Movie safe-fit fraction", "movie_safe_fit_fraction")
    r = add_entry(tab_eeg, r, "Custom movie width px (0 = unused)", "movie_custom_width_px")
    r = add_entry(tab_eeg, r, "Custom movie height px (0 = unused)", "movie_custom_height_px")
    ttk.Label(tab_eeg, text="Use movie_display_mode=safe_fit and fraction 0.90-0.94 to pull baked-in upper-right cues away from the physical screen edge.", foreground="#555555", wraplength=700).grid(row=r, column=0, columnspan=4, sticky="w", pady=(4, 8))

    # Watchdog tab
    r = 0
    r = section(tab_watch, r, "Live EEG sample-flow watchdog")
    r = add_bool(tab_watch, r, "Enable live EEG watchdog", "enable_eeg_watchdog")
    r = add_entry(tab_watch, r, "EEG watchdog stream name", "eeg_watchdog_stream_name")
    r = add_entry(tab_watch, r, "Expected EEG rate Hz", "eeg_watchdog_expected_rate_hz")
    r = add_entry(tab_watch, r, "Warning gap seconds", "eeg_watchdog_warning_gap_sec")
    r = add_entry(tab_watch, r, "Invalid dropout gap seconds", "eeg_watchdog_invalid_gap_sec")
    r = add_entry(tab_watch, r, "Rate warning Hz", "eeg_watchdog_rate_warn_hz")
    r = add_entry(tab_watch, r, "Rate invalid Hz", "eeg_watchdog_rate_invalid_hz")
    ttk.Label(
        tab_watch,
        text="Start BrainFlow-to-LSL first, then validate this stream before launching the experiment.",
        foreground="#555555",
        wraplength=700,
    ).grid(row=r, column=0, columnspan=4, sticky="w", pady=(6, 0))

    status_var = tk.StringVar(value="Ready. Select files, then Validate Inputs or press Ctrl+Enter to launch.")
    bottom = ttk.Frame(root, padding=(12, 4, 12, 10))
    bottom.grid(row=2, column=0, sticky="ew")
    bottom.columnconfigure(0, weight=1)
    ttk.Label(bottom, textvariable=status_var, foreground="#1f4e79", anchor="w").grid(row=0, column=0, columnspan=4, sticky="ew", pady=(0, 6))

    def build_cfg_from_vars() -> Dict[str, Any]:
        return {
            "participant_id": vars_s["participant_id"].get().strip(),
            "session_id": vars_s["session_id"].get().strip(),
            "run_label": vars_s["run_label"].get().strip(),
            "control_video": vars_s["control_video"].get().strip(),
            "target_video": vars_s["target_video"].get().strip(),
            "override_video": vars_s["override_video"].get().strip(),
            "cue_schedule_json": vars_s["cue_schedule_json"].get().strip(),
            "expected_sum_manual": vars_s["expected_sum_manual"].get().strip(),
            "baseline_seconds": parse_float(vars_s["baseline_seconds"].get(), 120.0),
            "washout_seconds": parse_float(vars_s["washout_seconds"].get(), 120.0),
            "stillness_reset_seconds": clamp_float(parse_float(vars_s["stillness_reset_seconds"].get(), DEFAULT_STILLNESS_RESET_SEC), MIN_STILLNESS_RESET_SEC, MAX_STILLNESS_RESET_SEC),
            "enable_final_reflection_baseline": bool(vars_s["enable_final_reflection_baseline"].get()),
            "final_reflection_baseline_seconds": parse_float(vars_s["final_reflection_baseline_seconds"].get(), DEFAULT_FINAL_REFLECTION_BASELINE_SEC),
            "movie_display_mode": vars_s["movie_display_mode"].get().strip().lower() or "safe_fit",
            "movie_safe_fit_fraction": clamp_float(parse_float(vars_s["movie_safe_fit_fraction"].get(), DEFAULT_MOVIE_SAFE_FIT_FRACTION), 0.50, 1.00),
            "movie_custom_width_px": parse_int(vars_s["movie_custom_width_px"].get(), 0),
            "movie_custom_height_px": parse_int(vars_s["movie_custom_height_px"].get(), 0),
            "use_standard_channel_map": bool(vars_s["use_standard_channel_map"].get()),
            "channel_map_confirmed": bool(vars_s["channel_map_confirmed"].get()),
            "channel_map_confidence": vars_s["channel_map_confidence"].get().strip().upper() or "UNKNOWN",
            "channel_map_label": vars_s["channel_map_label"].get().strip() or "PRAYCG16_FIXED_ORDER_v1",
            "channel_map_notes": vars_s["channel_map_notes"].get().strip(),
            "fullscreen": bool(vars_s["fullscreen"].get()),
            "screen_index": parse_int(vars_s["screen_index"].get(), 0),
            "log_dir": vars_s["log_dir"].get().strip() or "praycg_run_logs",
            "reward_text": vars_s["reward_text"].get(),
            "config_gui_mode": "tkinter_compact_tabs_scrollable_v1_8",
            "enable_eeg_watchdog": bool(vars_s["enable_eeg_watchdog"].get()),
            "eeg_watchdog_stream_name": vars_s["eeg_watchdog_stream_name"].get().strip() or "obci_eeg1",
            "eeg_watchdog_expected_rate_hz": parse_float(vars_s["eeg_watchdog_expected_rate_hz"].get(), 125.0),
            "eeg_watchdog_warning_gap_sec": parse_float(vars_s["eeg_watchdog_warning_gap_sec"].get(), 1.0),
            "eeg_watchdog_invalid_gap_sec": parse_float(vars_s["eeg_watchdog_invalid_gap_sec"].get(), 3.0),
            "eeg_watchdog_rate_warn_hz": parse_float(vars_s["eeg_watchdog_rate_warn_hz"].get(), 115.0),
            "eeg_watchdog_rate_invalid_hz": parse_float(vars_s["eeg_watchdog_rate_invalid_hz"].get(), 100.0),
        }

    def validate(show_success: bool = True) -> bool:
        cfg = build_cfg_from_vars()
        errors = _validate_media_selection_dict(cfg)
        if errors:
            status_var.set("Validation failed. Fix the listed issue(s).")
            messagebox.showerror("PRAYCG1.8 validation failed", "\n".join(errors))
            return False
        try:
            cues, expected, _payload = load_cue_schedule(cfg["cue_schedule_json"])
            target_hash = file_sha256(cfg["target_video"])
            override_hash = file_sha256(cfg["override_video"])
            msg = (
                f"Validation passed. Cue events: {len(cues)}; expected sum: {expected if expected is not None else cfg.get('expected_sum_manual')}.\n"
                f"Target/Override hash match: {'YES' if target_hash == override_hash else 'NO'}."
            )
            status_var.set(msg)
            if show_success:
                messagebox.showinfo("PRAYCG1.8 validation passed", msg)
            return True
        except Exception as exc:
            status_var.set(f"Validation failed: {exc}")
            messagebox.showerror("PRAYCG1.8 validation failed", str(exc))
            return False

    def start_run() -> None:
        if not validate(show_success=False):
            return
        result.update(build_cfg_from_vars())
        root.destroy()

    def cancel() -> None:
        root.destroy()

    ttk.Button(bottom, text="Validate Inputs", command=lambda: validate(show_success=True)).grid(row=1, column=1, sticky="e", padx=(6, 0))
    ttk.Button(bottom, text="Run PRAYCG1.8", command=start_run).grid(row=1, column=2, sticky="e", padx=(6, 0))
    ttk.Button(bottom, text="Cancel", command=cancel).grid(row=1, column=3, sticky="e", padx=(6, 0))

    root.bind("<Control-Return>", lambda _event: start_run())
    root.bind("<Escape>", lambda _event: cancel())
    root.protocol("WM_DELETE_WINDOW", cancel)
    root.mainloop()

    if not result:
        core.quit()
    return result

def emit_media_selection_markers(
    outlet: StreamOutlet,
    logger: EventLogger,
    cfg: Dict[str, Any],
    cue_payload: Dict[str, Any],
) -> Dict[str, str]:
    """Log selected media/cue provenance and emit concise LSL markers."""
    hashes = {
        "control_video_sha256": file_sha256(str(cfg["control_video"])),
        "target_video_sha256": file_sha256(str(cfg["target_video"])),
        "override_video_sha256": file_sha256(str(cfg["override_video"])),
        "cue_schedule_json_sha256": file_sha256(str(cfg["cue_schedule_json"])),
    }
    run_config_path = logger.log_dir / f"{logger.csv_path.stem}_run_config_media_selection.json"
    safe_cfg = {k: (str(v) if isinstance(v, Path) else v) for k, v in cfg.items()}
    payload = {
        "schema": "PRAYCG1_8_run_media_selection_v1",
        "created_unix_time": time.time(),
        "config": safe_cfg,
        "hashes": hashes,
        "cue_schedule_summary": {
            "schema": cue_payload.get("schema"),
            "cue_count": len(cue_payload.get("cue_events", [])) if isinstance(cue_payload.get("cue_events"), list) else None,
            "expected_sum": cue_payload.get("expected_sum"),
            "input_video": cue_payload.get("input_video"),
            "output_cued_video": cue_payload.get("output_cued_video"),
            "output_override_video": cue_payload.get("output_override_video"),
            "cue_design": cue_payload.get("cue_design", {}),
        },
        "target_override_hash_match": hashes["target_video_sha256"] == hashes["override_video_sha256"],
    }
    run_config_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    push_marker(outlet, logger, "MEDIA_SELECTION_GUI_VERSION_1.8", phase="SETUP", note=str(run_config_path))
    push_marker(outlet, logger, "MEDIA_FILE_SELECTION_START", phase="SETUP")
    push_marker(outlet, logger, "MEDIA_SELECTED_CONTROL_VIDEO", phase="SETUP", note=str(cfg["control_video"]))
    push_marker(outlet, logger, "MEDIA_SELECTED_TARGET_VIDEO", phase="SETUP", note=str(cfg["target_video"]))
    push_marker(outlet, logger, "MEDIA_SELECTED_CONTEXTUAL_OVERRIDE_VIDEO", phase="SETUP", note=str(cfg["override_video"]))
    push_marker(outlet, logger, "MEDIA_SELECTED_CUE_SCHEDULE_JSON", phase="SETUP", note=str(cfg["cue_schedule_json"]))
    push_marker(outlet, logger, f"MEDIA_SHA256_CONTROL_{hashes['control_video_sha256'][:12]}", phase="SETUP", note=hashes["control_video_sha256"])
    push_marker(outlet, logger, f"MEDIA_SHA256_TARGET_{hashes['target_video_sha256'][:12]}", phase="SETUP", note=hashes["target_video_sha256"])
    push_marker(outlet, logger, f"MEDIA_SHA256_OVERRIDE_{hashes['override_video_sha256'][:12]}", phase="SETUP", note=hashes["override_video_sha256"])
    push_marker(outlet, logger, f"MEDIA_SHA256_CUEJSON_{hashes['cue_schedule_json_sha256'][:12]}", phase="SETUP", note=hashes["cue_schedule_json_sha256"])
    push_marker(outlet, logger, f"TARGET_OVERRIDE_HASH_MATCH_{'TRUE' if hashes['target_video_sha256'] == hashes['override_video_sha256'] else 'FALSE'}", phase="SETUP")
    push_marker(outlet, logger, "MEDIA_FILE_SELECTION_END", phase="SETUP", note=str(run_config_path))
    return hashes

def run_full_experiment() -> None:
    logging.console.setLevel(logging.WARNING)
    cfg = collect_gui_config()

    log_dir = Path(str(cfg["log_dir"])).expanduser().resolve()
    logger = EventLogger(log_dir, str(cfg["participant_id"]), str(cfg["session_id"]), str(cfg["run_label"]))

    source_id = f"praycg_stasismarkers_{sanitize_for_filename(str(cfg['participant_id']))}_{sanitize_for_filename(str(cfg['session_id']))}_{uuid.uuid4().hex[:10]}"
    info = StreamInfo("StasisMarkers", "Markers", 1, 0, "string", source_id)
    desc = info.desc()
    desc.append_child_value("protocol", "PRAYCG")
    desc.append_child_value("protocol_version", "1.8")
    desc.append_child_value("source_id", source_id)
    desc.append_child_value("marker_capture_rule", "Start LabRecorder only after LSL_PREFLIGHT_HOLD_START appears and StasisMarkers is visible.")
    outlet = StreamOutlet(info, chunk_size=1, max_buffered=3600)
    core.wait(0.75)
    logger.log("LOCAL_LOG_CREATED", phase="SETUP", note=str(logger.csv_path))
    push_marker(outlet, logger, "STASIS_MARKER_STREAM_ONLINE", phase="SETUP", note=source_id)
    push_marker(outlet, logger, "PRAYCG_VERSION_1.8", phase="SETUP")
    push_marker(outlet, logger, "STASIS_MARKER_SOURCE_ID_RECORDED", phase="SETUP", note=source_id)
    push_marker(outlet, logger, "LABRECORDER_START_AFTER_THIS_MARKER_STREAM_IS_ONLINE", phase="SETUP")
    push_marker(outlet, logger, f"STILLNESS_RESET_SECONDS_{float(cfg['stillness_reset_seconds']):.1f}", phase="SETUP")
    push_marker(outlet, logger, f"REPORT_INPUT_EXCLUSION_PREPAD_SEC_{REPORT_INPUT_EXCLUSION_PREPAD_SEC:.1f}", phase="SETUP")
    push_marker(outlet, logger, f"REPORT_INPUT_EXCLUSION_POSTPAD_SEC_{REPORT_INPUT_EXCLUSION_POSTPAD_SEC:.1f}", phase="SETUP")
    push_marker(outlet, logger, f"FINAL_REFLECTION_BASELINE_ENABLED_{'TRUE' if bool(cfg.get('enable_final_reflection_baseline', True)) else 'FALSE'}", phase="SETUP")
    push_marker(outlet, logger, f"FINAL_REFLECTION_BASELINE_SECONDS_{float(cfg.get('final_reflection_baseline_seconds', DEFAULT_FINAL_REFLECTION_BASELINE_SEC)):.1f}", phase="SETUP")
    push_marker(outlet, logger, f"MOVIE_DISPLAY_MODE_{sanitize_marker_part(str(cfg.get('movie_display_mode', 'safe_fit')).lower())}", phase="SETUP")
    push_marker(outlet, logger, f"MOVIE_SAFE_FIT_FRACTION_{float(cfg.get('movie_safe_fit_fraction', DEFAULT_MOVIE_SAFE_FIT_FRACTION)):.3f}", phase="SETUP")

    # v1.8: cue schedule and exact media paths are explicit GUI selections.
    # If the cue JSON cannot be loaded, hard-stop before the run instead of silently
    # continuing with missing cue markers / missing objective sum scoring.
    cue_events, expected_sum_from_schedule, cue_payload = load_cue_schedule(str(cfg["cue_schedule_json"]))
    if not cue_events:
        push_marker(outlet, logger, "ERROR_CUE_SCHEDULE_NOT_LOADED_ABORT", phase="SETUP", note=str(cfg["cue_schedule_json"]))
        logger.close()
        raise RuntimeError(f"Cue schedule did not load or had no cue_events: {cfg['cue_schedule_json']}")
    emit_media_selection_markers(outlet, logger, cfg, cue_payload)

    if bool(cfg.get("use_standard_channel_map", True)):
        emit_channel_map_markers(
            outlet,
            logger,
            PRAYCG16_FIXED_CHANNEL_MAP,
            map_label=str(cfg.get("channel_map_label", "PRAYCG16_FIXED_ORDER_v1")),
            confirmed=bool(cfg.get("channel_map_confirmed", False)),
            confidence=str(cfg.get("channel_map_confidence", "UNKNOWN")),
            notes=str(cfg.get("channel_map_notes", "")),
        )
    else:
        push_marker(outlet, logger, "CHANNEL_MAP_NOT_EMITTED", phase="SETUP", note="use_standard_channel_map=False")
        push_marker(outlet, logger, "CHANNEL_MAP_UNCONFIRMED_DO_NOT_USE_ROI", phase="SETUP", note="No channel map emitted.")

    expected_sum: Optional[int] = expected_sum_from_schedule
    if str(cfg["expected_sum_manual"]).strip():
        expected_sum = parse_int(cfg["expected_sum_manual"], expected_sum_from_schedule or -1)
    if expected_sum is not None and expected_sum >= 0:
        push_marker(outlet, logger, f"CUE_SCHEDULE_EXPECTED_SUM_{expected_sum}", phase="SETUP")
    if cue_events:
        push_marker(outlet, logger, f"CUE_SCHEDULE_LOADED_N_{len(cue_events)}", phase="SETUP", note=str(cfg["cue_schedule_json"]))
    else:
        push_marker(outlet, logger, "CUE_SCHEDULE_NOT_LOADED", phase="SETUP", note=str(cfg["cue_schedule_json"]))

    # Stream inventory snapshot. This is only advisory; LabRecorder is the ground truth.
    stream_names = resolve_stream_names(timeout=0.75)
    logger.log("STREAM_INVENTORY", phase="SETUP", note=",".join(stream_names))

    # v1.8: optional live EEG watchdog. This checks that obci_eeg1 is actively
    # producing samples, not merely visible as an LSL stream header.
    global ACTIVE_EEG_WATCHDOG
    ACTIVE_EEG_WATCHDOG = None
    if bool(cfg.get("enable_eeg_watchdog", True)):
        ACTIVE_EEG_WATCHDOG = LSLEEGWatchdog(
            outlet,
            logger,
            stream_name=str(cfg.get("eeg_watchdog_stream_name", "obci_eeg1")),
            expected_rate_hz=float(cfg.get("eeg_watchdog_expected_rate_hz", 125.0)),
            warning_gap_sec=float(cfg.get("eeg_watchdog_warning_gap_sec", 1.0)),
            invalid_gap_sec=float(cfg.get("eeg_watchdog_invalid_gap_sec", 3.0)),
            rate_warn_hz=float(cfg.get("eeg_watchdog_rate_warn_hz", 115.0)),
            rate_invalid_hz=float(cfg.get("eeg_watchdog_rate_invalid_hz", 100.0)),
        )
        if not ACTIVE_EEG_WATCHDOG.connect():
            push_marker(outlet, logger, "ERROR_EEG_WATCHDOG_STREAM_NOT_FOUND_ABORT", phase="SETUP", note=str(cfg.get("eeg_watchdog_stream_name", "obci_eeg1")))
            logger.close()
            raise RuntimeError("EEG watchdog could not resolve the live EEG stream. Start BrainFlow-to-LSL first.")
        # Pull a few seconds before LabRecorder hold so the operator knows the stream is live.
        precheck_clock = core.Clock()
        push_marker(outlet, logger, "EEG_WATCHDOG_PREFLIGHT_SAMPLE_CHECK_START", phase="SETUP")
        while precheck_clock.getTime() < 3.0:
            tick_eeg_watchdog(outlet, logger, "SETUP")
            core.wait(0.02)
        push_marker(outlet, logger, "EEG_WATCHDOG_PREFLIGHT_SAMPLE_CHECK_END", phase="SETUP", note=ACTIVE_EEG_WATCHDOG.final_note())


    win = None

    # v1.6L/v1.6R correction: keep the LabRecorder preflight as a normal window so the
    # operator can Alt-Tab / click LabRecorder Update / Start without being trapped
    # inside a fullscreen black PsychoPy window. The StasisMarkers outlet is already
    # online at this point and LSL_PREFLIGHT_PING markers are being emitted.
    preflight_win = visual.Window(
        size=(980, 680),
        fullscr=False,
        screen=0,
        units="pix",
        color=[-1, -1, -1],
        allowGUI=True,
    )
    try:
        wait_for_right_click(preflight_win, outlet, logger)
    finally:
        try:
            preflight_win.close()
        except Exception:
            pass
    core.wait(0.35)

    # Only now enter the experiment display mode. This is the first fullscreen window.
    win = visual.Window(
        size=(1920, 1080),
        fullscr=bool(cfg["fullscreen"]),
        screen=int(cfg["screen_index"]),
        units="pix",
        color=[-1, -1, -1],
        allowGUI=False,
    )
    fixation = visual.TextStim(win, text="+", color="white", height=56)
    natural_movie_size = _extract_video_size_from_payload(cue_payload)
    movie_draw_size = calculate_movie_draw_size(win, cfg, natural_movie_size)
    push_marker(outlet, logger, f"MOVIE_NATURAL_SIZE_{natural_movie_size[0]}x{natural_movie_size[1]}", phase="SETUP")
    push_marker(outlet, logger, f"MOVIE_DRAW_SIZE_{movie_draw_size[0]}x{movie_draw_size[1]}", phase="SETUP")

    try:
        push_marker(outlet, logger, "PROTOCOL_SEQUENCE_START", phase="PROTOCOL")

        run_baseline(win, outlet, logger, fixation, duration=float(cfg["baseline_seconds"]), phase_name="BASELINE_1")

        show_instruction_wait_then_stillness(
            win,
            outlet,
            logger,
            "Control block.\n\nWatch the screen naturally. Keep your eyes forward and stay relaxed.",
            phase="CONTROL_1",
            marker_prefix="CONTROL_1_INSTRUCTION",
            stillness_duration=float(cfg["stillness_reset_seconds"]),
            stillness_phase_name="CONTROL_1_PRE_START_STILLNESS",
            stillness_reason="after_control_instruction_proceed_before_control_video",
        )
        play_video(win, outlet, logger, str(cfg["control_video"]), phase_name="CONTROL_1", cue_events=(), emit_cue_markers=False, movie_draw_size=movie_draw_size)
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_1")
        collect_phase_ratings(win, outlet, logger, phase_name="CONTROL_1_AFTER_WASHOUT_1")

        show_instruction_wait_then_stillness(
            win,
            outlet,
            logger,
            (
                "Target block.\n\n"
                "Watch naturally. Let the story land if it lands.\n"
                "Small numbers may appear. Ignore them. Do not count them."
            ),
            phase="TARGET_1",
            marker_prefix="TARGET_1_INSTRUCTION",
            stillness_duration=float(cfg["stillness_reset_seconds"]),
            stillness_phase_name="TARGET_1_PRE_START_STILLNESS",
            stillness_reason="after_target_instruction_proceed_before_target_video",
        )
        play_video(win, outlet, logger, str(cfg["target_video"]), phase_name="TARGET_1", cue_events=cue_events, emit_cue_markers=True, movie_draw_size=movie_draw_size)
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_2")
        collect_phase_ratings(win, outlet, logger, phase_name="TARGET_1_AFTER_WASHOUT_2")

        expected_text = "" if expected_sum is None else "The correct answer is stored privately and will be checked after you respond."
        show_instruction_wait_then_stillness(
            win,
            outlet,
            logger,
            (
                "Contextual Override block.\n\n"
                "Watch the same story, but this time perform the counting task.\n"
                "Every time a number appears, add it to a running sum in your head.\n"
                "You will type the final sum immediately after the video.\n"
                f"{expected_text}"
            ),
            phase="CONTEXTUAL_OVERRIDE_1",
            marker_prefix="CONTEXTUAL_OVERRIDE_1_INSTRUCTION",
            stillness_duration=float(cfg["stillness_reset_seconds"]),
            stillness_phase_name="CONTEXTUAL_OVERRIDE_1_PRE_START_STILLNESS",
            stillness_reason="after_override_instruction_proceed_before_override_video",
        )
        if expected_sum is not None:
            push_marker(outlet, logger, f"CONTEXTUAL_OVERRIDE_1_EXPECTED_SUM_{expected_sum}", phase="CONTEXTUAL_OVERRIDE_1")
        play_video(
            win,
            outlet,
            logger,
            str(cfg["override_video"]),
            phase_name="CONTEXTUAL_OVERRIDE_1",
            cue_events=cue_events,
            emit_cue_markers=True,
            movie_draw_size=movie_draw_size,
        )
        collect_numeric_response(
            win,
            outlet,
            logger,
            phase_name="CONTEXTUAL_OVERRIDE_1",
            expected_sum=expected_sum,
            reward_text=str(cfg["reward_text"]),
        )
        return_to_stillness(
            win, outlet, logger,
            phase_name="CONTEXTUAL_OVERRIDE_1_SUM_ENTRY",
            duration=float(cfg["stillness_reset_seconds"]),
            reason="after_sum_input_before_washout_3",
        )
        run_baseline(win, outlet, logger, fixation, duration=float(cfg["washout_seconds"]), phase_name="WASHOUT_3")
        collect_phase_ratings(win, outlet, logger, phase_name="OVERRIDE_1_AFTER_WASHOUT_3")

        if bool(cfg.get("enable_final_reflection_baseline", True)):
            show_instruction_wait_then_stillness(
                win,
                outlet,
                logger,
                (
                    "Final reflection baseline.\n\n"
                    "Before the final two-minute baseline, reflect quietly on the three video blocks.\n"
                    "Compare how the scrambled/static Control, the natural Target, and the Contextual Override felt emotionally in relation to each other.\n"
                    "Do not type yet. After you press SPACE, sit back, settle, and let the comparison rest in mind while staying still."
                ),
                phase="BASELINE_2_REFLECTION",
                marker_prefix="BASELINE_2_REFLECTION_INSTRUCTION",
                stillness_duration=float(cfg["stillness_reset_seconds"]),
                stillness_phase_name="BASELINE_2_REFLECTION_PRE_START_STILLNESS",
                stillness_reason="after_washout3_reports_before_final_reflection_baseline",
            )
            run_baseline(
                win,
                outlet,
                logger,
                fixation,
                duration=float(cfg.get("final_reflection_baseline_seconds", DEFAULT_FINAL_REFLECTION_BASELINE_SEC)),
                phase_name="BASELINE_2_REFLECTION",
            )
            collect_final_master_report(win, outlet, logger)
        else:
            push_marker(outlet, logger, "FINAL_REFLECTION_BASELINE_SKIPPED", phase="PROTOCOL")

        push_marker(outlet, logger, "PROTOCOL_SEQUENCE_END", phase="PROTOCOL")
        if ACTIVE_EEG_WATCHDOG is not None:
            push_marker(outlet, logger, "EEG_WATCHDOG_FINAL_SUMMARY", phase="PROTOCOL", note=ACTIVE_EEG_WATCHDOG.final_note())
    finally:
        logger.close()
        try:
            if win is not None:
                win.close()
        except Exception:
            pass
        core.quit()


if __name__ == "__main__":
    run_full_experiment()
