#!/usr/bin/env python3
"""
PRAYCG MediaPrep GUI v1.6M

One-master-MP4 media preparation pipeline for PR-AYC-G.

Given one master .mp4, this tool creates:
  1. cue-embedded Target MP4
  2. bit-identical cue-embedded Contextual Override MP4
  3. phase-scrambled Control MP4 generated from the cue-embedded Target
  4. cue schedule JSON/CSV with expected running-sum answer
  5. media-prep manifest and short Markdown report

Design intent:
  - Target and Contextual Override should use the same cue-embedded video.
  - Only instructions differ: Target = ignore numbers / watch naturally;
    Override = add numbers / report sum.
  - The Control is generated by phase-scrambling the cue-embedded target so that
    the control inherits the same cue-timing/low-level media events while removing
    recognizable narrative structure.

This is a preparation tool, not an experimental runner.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import hashlib
import json
import math
import os
import random
import shutil
import subprocess
import sys
import tempfile
import threading
import traceback
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    import cv2
except Exception as exc:  # pragma: no cover
    raise RuntimeError("opencv-python is required. Install with: pip install opencv-python") from exc

try:
    from scipy import signal
    from scipy.io import wavfile
except Exception as exc:  # pragma: no cover
    raise RuntimeError("scipy is required. Install with: pip install scipy") from exc

try:
    from moviepy import VideoFileClip  # MoviePy 2.x
except Exception:  # pragma: no cover
    try:
        from moviepy.editor import VideoFileClip  # MoviePy 1.x
    except Exception as exc:
        raise RuntimeError("moviepy is required. Install with: pip install moviepy") from exc


SCHEMA = "PRAYCG_media_prep_suite_v1_6M"
DEFAULT_SEED = 20260724


@dataclass
class CueEvent:
    cue_index: int
    value: int
    start_sec: float
    end_sec: float
    duration_sec: float
    interval_sec: float
    position: str
    badge_x1: int = 0
    badge_y1: int = 0
    badge_x2: int = 0
    badge_y2: int = 0
    pre_badge_background_luminance: Optional[float] = None
    contrast_pre_badge_0_1: Optional[float] = None
    contrast_protected_badge: bool = True


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()


def now_utc_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat()


def sanitize_name(name: str) -> str:
    allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
    out = "".join(c if c in allowed else "_" for c in name.strip())
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_") or "PRAYCG_Stimulus"


def get_video_props(path: Path) -> Dict[str, Any]:
    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {path}")
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 0)
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 0)
    duration = frame_count / fps if fps > 0 else 0.0
    cap.release()
    return {
        "fps": fps,
        "frame_count": frame_count,
        "width": width,
        "height": height,
        "duration_sec": duration,
    }


def make_cue_schedule(
    duration_sec: float,
    seed: int,
    interval_sec: float,
    display_duration_sec: float,
    start_delay_sec: float,
    min_value: int,
    max_value: int,
    position: str,
) -> List[CueEvent]:
    if interval_sec <= 0:
        raise ValueError("interval_sec must be > 0")
    if display_duration_sec <= 0:
        raise ValueError("display_duration_sec must be > 0")
    if display_duration_sec > interval_sec:
        raise ValueError("display_duration_sec should not exceed interval_sec")
    if min_value > max_value:
        raise ValueError("min_value cannot exceed max_value")
    rng = random.Random(int(seed))
    events: List[CueEvent] = []
    t = float(start_delay_sec)
    idx = 1
    # Leave a tiny safety margin at the end.
    while t + display_duration_sec <= duration_sec - 0.05:
        val = rng.randint(int(min_value), int(max_value))
        events.append(
            CueEvent(
                cue_index=idx,
                value=val,
                start_sec=round(t, 6),
                end_sec=round(t + display_duration_sec, 6),
                duration_sec=float(display_duration_sec),
                interval_sec=float(interval_sec),
                position=position,
            )
        )
        idx += 1
        t += float(interval_sec)
    return events


def luminance_mean_bgr(region: np.ndarray) -> float:
    if region.size == 0:
        return float("nan")
    # BGR to luminance. Coefficients for RGB, applied to BGR order.
    b = region[:, :, 0].astype(np.float32)
    g = region[:, :, 1].astype(np.float32)
    r = region[:, :, 2].astype(np.float32)
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return float(np.nanmean(y))


def contrast_0_1(text_luma: float, bg_luma: float) -> float:
    return float(abs(text_luma - bg_luma) / (text_luma + bg_luma + 1e-6))


def badge_geometry(frame_shape: Tuple[int, int, int], text: str, position: str, font_scale_factor: float) -> Tuple[int, int, int, int, float, int]:
    h, w = frame_shape[:2]
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = max(0.8, min(2.2, (h / 1080.0) * float(font_scale_factor)))
    thickness = max(2, int(round(h / 420)))
    (tw, th), baseline = cv2.getTextSize(str(text), font, font_scale, thickness)
    pad_x = max(16, int(round(w * 0.014)))
    pad_y = max(12, int(round(h * 0.014)))
    badge_w = tw + 2 * pad_x
    badge_h = th + baseline + 2 * pad_y
    margin_x = max(28, int(round(w * 0.035)))
    margin_y = max(28, int(round(h * 0.045)))

    pos = position.lower().strip()
    if pos == "upper_right":
        x2 = w - margin_x
        x1 = x2 - badge_w
        y1 = margin_y
        y2 = y1 + badge_h
    elif pos == "upper_left":
        x1 = margin_x
        x2 = x1 + badge_w
        y1 = margin_y
        y2 = y1 + badge_h
    elif pos == "lower_right":
        x2 = w - margin_x
        x1 = x2 - badge_w
        y2 = h - margin_y
        y1 = y2 - badge_h
    elif pos == "lower_left":
        x1 = margin_x
        x2 = x1 + badge_w
        y2 = h - margin_y
        y1 = y2 - badge_h
    else:
        raise ValueError(f"Unsupported position: {position}. Use upper_right, upper_left, lower_right, lower_left.")

    x1 = int(max(0, min(w - 1, x1)))
    x2 = int(max(1, min(w, x2)))
    y1 = int(max(0, min(h - 1, y1)))
    y2 = int(max(1, min(h, y2)))
    return x1, y1, x2, y2, font_scale, thickness


def draw_number_badge(
    frame_bgr: np.ndarray,
    number: int,
    position: str = "upper_right",
    alpha: float = 0.78,
    font_scale_factor: float = 0.95,
) -> Tuple[np.ndarray, Tuple[int, int, int, int], float, float]:
    """Draw a contrast-protected number badge and return frame + badge bbox + pre-bg luma + pre-contrast."""
    out = frame_bgr.copy()
    text = str(number)
    x1, y1, x2, y2, font_scale, thickness = badge_geometry(out.shape, text, position, font_scale_factor)
    bg_region = out[y1:y2, x1:x2]
    bg_luma = luminance_mean_bgr(bg_region)
    pre_contrast = contrast_0_1(255.0, bg_luma if math.isfinite(bg_luma) else 0.0)

    overlay = out.copy()
    # Dark badge with a pale border. This is the main v1.6M change: numbers no longer disappear on white backgrounds.
    cv2.rectangle(overlay, (x1, y1), (x2, y2), (0, 0, 0), -1)
    cv2.addWeighted(overlay, float(alpha), out, 1.0 - float(alpha), 0, out)
    cv2.rectangle(out, (x1, y1), (x2, y2), (230, 230, 230), max(1, thickness // 2))

    font = cv2.FONT_HERSHEY_SIMPLEX
    (tw, th), baseline = cv2.getTextSize(text, font, font_scale, thickness)
    tx = x1 + (x2 - x1 - tw) // 2
    ty = y1 + (y2 - y1 + th) // 2
    # Black outline then white text, readable against badge.
    cv2.putText(out, text, (tx, ty), font, font_scale, (0, 0, 0), thickness + 4, cv2.LINE_AA)
    cv2.putText(out, text, (tx, ty), font, font_scale, (255, 255, 255), thickness, cv2.LINE_AA)
    return out, (x1, y1, x2, y2), bg_luma, pre_contrast


def find_active_cue(t_sec: float, events: List[CueEvent]) -> Optional[CueEvent]:
    # Cue count is modest; linear search is sufficient and clearer.
    for ev in events:
        if ev.start_sec <= t_sec < ev.end_sec:
            return ev
    return None


def ffmpeg_exists() -> bool:
    return shutil.which("ffmpeg") is not None


def mux_original_audio(source_mp4: Path, video_no_audio_mp4: Path, output_mp4: Path, fps: float) -> None:
    """Attach original audio to a rendered no-audio video. Prefer ffmpeg; fallback to MoviePy."""
    if ffmpeg_exists():
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_no_audio_mp4),
            "-i", str(source_mp4),
            "-map", "0:v:0",
            "-map", "1:a?",
            "-c:v", "copy",
            "-c:a", "aac",
            "-shortest",
            str(output_mp4),
        ]
        subprocess.run(cmd, check=True)
        return

    # Fallback.
    src_clip = VideoFileClip(str(source_mp4))
    vid_clip = VideoFileClip(str(video_no_audio_mp4))
    try:
        if src_clip.audio is not None:
            if hasattr(vid_clip, "with_audio"):
                out_clip = vid_clip.with_audio(src_clip.audio)
            else:  # MoviePy 1.x
                out_clip = vid_clip.set_audio(src_clip.audio)
        else:
            out_clip = vid_clip
        out_clip.write_videofile(str(output_mp4), codec="libx264", audio_codec="aac", fps=fps)
    finally:
        try:
            src_clip.close()
        except Exception:
            pass
        try:
            vid_clip.close()
        except Exception:
            pass


def mux_wav_audio(video_no_audio_mp4: Path, wav_path: Path, output_mp4: Path) -> None:
    if ffmpeg_exists():
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_no_audio_mp4),
            "-i", str(wav_path),
            "-map", "0:v:0",
            "-map", "1:a:0",
            "-c:v", "copy",
            "-c:a", "aac",
            "-shortest",
            str(output_mp4),
        ]
        subprocess.run(cmd, check=True)
        return

    # Fallback using MoviePy.
    try:
        from moviepy import AudioFileClip
    except Exception:
        from moviepy.editor import AudioFileClip
    vid_clip = VideoFileClip(str(video_no_audio_mp4))
    aud_clip = AudioFileClip(str(wav_path))
    try:
        out_clip = vid_clip.with_audio(aud_clip) if hasattr(vid_clip, "with_audio") else vid_clip.set_audio(aud_clip)
        out_clip.write_videofile(str(output_mp4), codec="libx264", audio_codec="aac", fps=vid_clip.fps)
    finally:
        try: vid_clip.close()
        except Exception: pass
        try: aud_clip.close()
        except Exception: pass


def render_cued_video(
    master_mp4: Path,
    output_cued_mp4: Path,
    events: List[CueEvent],
    position: str,
    badge_alpha: float,
    font_scale_factor: float,
    overwrite: bool,
    progress_cb=None,
    max_seconds: Optional[float] = None,
) -> Dict[str, Any]:
    if output_cued_mp4.exists() and not overwrite:
        raise FileExistsError(f"Output exists: {output_cued_mp4}")

    props = get_video_props(master_mp4)
    fps = props["fps"]
    width = props["width"]
    height = props["height"]
    frame_count = props["frame_count"]
    if fps <= 0 or frame_count <= 0:
        raise RuntimeError("Invalid video FPS/frame count")

    if max_seconds is not None and max_seconds > 0:
        frame_limit = min(frame_count, int(round(max_seconds * fps)))
    else:
        frame_limit = frame_count

    cap = cv2.VideoCapture(str(master_mp4))
    if not cap.isOpened():
        raise RuntimeError(f"Could not open {master_mp4}")

    tmp_dir = Path(tempfile.mkdtemp(prefix="praycg_v16M_cued_"))
    tmp_video = tmp_dir / "cued_no_audio.mp4"
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(tmp_video), fourcc, fps, (width, height))
    if not writer.isOpened():
        cap.release()
        raise RuntimeError("Could not open cv2 VideoWriter for cued video")

    cue_first_frame_seen: Dict[int, bool] = {}
    processed = 0
    try:
        for frame_idx in range(frame_limit):
            ok, frame = cap.read()
            if not ok:
                break
            t = frame_idx / fps
            ev = find_active_cue(t, events)
            if ev is not None:
                frame, bbox, bg_luma, pre_contrast = draw_number_badge(
                    frame,
                    ev.value,
                    position=position,
                    alpha=badge_alpha,
                    font_scale_factor=font_scale_factor,
                )
                if ev.cue_index not in cue_first_frame_seen:
                    ev.badge_x1, ev.badge_y1, ev.badge_x2, ev.badge_y2 = bbox
                    ev.pre_badge_background_luminance = bg_luma
                    ev.contrast_pre_badge_0_1 = pre_contrast
                    cue_first_frame_seen[ev.cue_index] = True
            writer.write(frame)
            processed += 1
            if progress_cb and (frame_idx % max(1, int(fps * 2)) == 0):
                progress_cb(f"Cue render: frame {frame_idx+1}/{frame_limit}")
    finally:
        writer.release()
        cap.release()

    # Preserve original audio in target/override video.
    if progress_cb:
        progress_cb("Muxing original audio into cued Target video...")
    mux_original_audio(master_mp4, tmp_video, output_cued_mp4, fps=fps)

    try:
        shutil.rmtree(tmp_dir)
    except Exception:
        pass

    return {**props, "rendered_frames": processed, "rendered_duration_sec": processed / fps if fps else None}


def phase_scramble_frame_bgr(frame_bgr: np.ndarray, rng: np.random.Generator, contrast_strength: float = 0.65) -> np.ndarray:
    # Process each color channel independently, preserving channel mean/std approximately.
    frame = frame_bgr.astype(np.float32)
    out = np.zeros_like(frame)
    for ch in range(3):
        x = frame[:, :, ch]
        orig_mean = float(np.mean(x))
        orig_std = float(np.std(x) + 1e-6)
        fft = np.fft.rfft2(x)
        amp = np.abs(fft)
        phase = rng.uniform(-np.pi, np.pi, size=fft.shape)
        # Preserve DC phase/mean more stably by zeroing random phase for DC.
        phase[0, 0] = 0.0
        y = np.fft.irfft2(amp * np.exp(1j * phase), s=x.shape)
        y_std = float(np.std(y) + 1e-6)
        y = (y - float(np.mean(y))) * (orig_std / y_std) + orig_mean
        out[:, :, ch] = y
    out = 128.0 + float(contrast_strength) * (out - 128.0)
    return np.clip(out, 0, 255).astype(np.uint8)


def render_phase_scrambled_video_no_audio(
    input_mp4: Path,
    output_no_audio_mp4: Path,
    seed: int,
    contrast_strength: float,
    overwrite: bool,
    progress_cb=None,
    max_seconds: Optional[float] = None,
) -> Dict[str, Any]:
    if output_no_audio_mp4.exists() and not overwrite:
        raise FileExistsError(f"Output exists: {output_no_audio_mp4}")
    props = get_video_props(input_mp4)
    fps = props["fps"]
    width = props["width"]
    height = props["height"]
    frame_count = props["frame_count"]
    if max_seconds is not None and max_seconds > 0:
        frame_limit = min(frame_count, int(round(max_seconds * fps)))
    else:
        frame_limit = frame_count

    cap = cv2.VideoCapture(str(input_mp4))
    if not cap.isOpened():
        raise RuntimeError(f"Could not open {input_mp4}")
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(output_no_audio_mp4), fourcc, fps, (width, height))
    if not writer.isOpened():
        cap.release()
        raise RuntimeError("Could not open cv2 VideoWriter for scrambled video")

    processed = 0
    try:
        for frame_idx in range(frame_limit):
            ok, frame = cap.read()
            if not ok:
                break
            rng = np.random.default_rng(int(seed) + frame_idx * 1009)
            y = phase_scramble_frame_bgr(frame, rng, contrast_strength=contrast_strength)
            writer.write(y)
            processed += 1
            if progress_cb and (frame_idx % max(1, int(fps * 2)) == 0):
                progress_cb(f"Phase-scramble video: frame {frame_idx+1}/{frame_limit}")
    finally:
        writer.release()
        cap.release()
    return {**props, "rendered_frames": processed, "rendered_duration_sec": processed / fps if fps else None}


def has_audio(input_mp4: Path) -> bool:
    try:
        clip = VideoFileClip(str(input_mp4))
        try:
            return clip.audio is not None
        finally:
            clip.close()
    except Exception:
        return False


def scramble_audio_to_wav(
    input_mp4: Path,
    output_wav: Path,
    seed: int,
    audio_fps: int = 44100,
    nperseg: int = 4096,
    noverlap: int = 3072,
    progress_cb=None,
) -> Optional[Dict[str, Any]]:
    if not has_audio(input_mp4):
        return None
    if progress_cb:
        progress_cb("Extracting audio for local phase scrambling...")
    clip = VideoFileClip(str(input_mp4))
    try:
        if clip.audio is None:
            return None
        arr = clip.audio.to_soundarray(fps=audio_fps)
    finally:
        try:
            clip.close()
        except Exception:
            pass

    arr = np.asarray(arr, dtype=np.float32)
    if arr.ndim == 1:
        arr = arr[:, None]
    original_rms = float(np.sqrt(np.mean(arr ** 2)) + 1e-12)
    rng = np.random.default_rng(int(seed) + 777777)
    out_chs = []
    for ch in range(arr.shape[1]):
        if progress_cb:
            progress_cb(f"Phase-scrambling audio channel {ch+1}/{arr.shape[1]}...")
        x = arr[:, ch]
        f, t, Z = signal.stft(x, fs=audio_fps, window="hann", nperseg=nperseg, noverlap=noverlap, boundary="zeros", padded=True)
        mag = np.abs(Z)
        random_phase = rng.uniform(-np.pi, np.pi, size=Z.shape)
        # Keep DC and Nyquist phase less extreme to reduce pops.
        random_phase[0, :] = 0.0
        Zs = mag * np.exp(1j * random_phase)
        _, y = signal.istft(Zs, fs=audio_fps, window="hann", nperseg=nperseg, noverlap=noverlap, input_onesided=True, boundary=True)
        y = y[: len(x)]
        out_chs.append(y.astype(np.float32))
    out = np.stack(out_chs, axis=1)
    out_rms = float(np.sqrt(np.mean(out ** 2)) + 1e-12)
    out = out * (original_rms / out_rms)
    out = np.clip(out, -0.98, 0.98)
    wavfile.write(str(output_wav), audio_fps, (out * 32767.0).astype(np.int16))
    return {
        "audio_fps": audio_fps,
        "channels": int(out.shape[1]),
        "samples": int(out.shape[0]),
        "duration_sec": float(out.shape[0] / audio_fps),
        "original_rms": original_rms,
        "scrambled_rms": float(np.sqrt(np.mean(out ** 2)) + 1e-12),
    }


def phase_scramble_media(
    input_cued_mp4: Path,
    output_control_mp4: Path,
    seed: int,
    contrast_strength: float,
    overwrite: bool,
    progress_cb=None,
    max_seconds: Optional[float] = None,
) -> Dict[str, Any]:
    if output_control_mp4.exists() and not overwrite:
        raise FileExistsError(f"Output exists: {output_control_mp4}")
    tmp_dir = Path(tempfile.mkdtemp(prefix="praycg_v16M_scramble_"))
    tmp_vid = tmp_dir / "control_no_audio.mp4"
    tmp_wav = tmp_dir / "control_audio_scrambled.wav"
    try:
        video_summary = render_phase_scrambled_video_no_audio(
            input_cued_mp4,
            tmp_vid,
            seed=seed,
            contrast_strength=contrast_strength,
            overwrite=True,
            progress_cb=progress_cb,
            max_seconds=max_seconds,
        )
        audio_summary = scramble_audio_to_wav(input_cued_mp4, tmp_wav, seed=seed, progress_cb=progress_cb)
        if audio_summary is not None:
            if progress_cb:
                progress_cb("Muxing scrambled audio into phase-scrambled control...")
            mux_wav_audio(tmp_vid, tmp_wav, output_control_mp4)
        else:
            shutil.copy2(tmp_vid, output_control_mp4)
        return {"video": video_summary, "audio": audio_summary, "source": str(input_cued_mp4)}
    finally:
        try:
            shutil.rmtree(tmp_dir)
        except Exception:
            pass


def write_schedule_files(
    events: List[CueEvent],
    json_path: Path,
    csv_path: Path,
    metadata: Dict[str, Any],
) -> None:
    event_dicts = [asdict(ev) for ev in events]
    payload = {**metadata, "cue_count": len(events), "expected_sum": int(sum(ev.value for ev in events)), "cue_events": event_dicts}
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(event_dicts[0].keys()) if event_dicts else ["cue_index", "value"])
        writer.writeheader()
        for row in event_dicts:
            writer.writerow(row)


def make_report(out_dir: Path, manifest: Dict[str, Any]) -> None:
    lines = []
    lines.append(f"# PRAYCG MediaPrep Suite v1.6M Report")
    lines.append("")
    lines.append(f"Created UTC: `{manifest.get('created_utc')}`")
    lines.append(f"Project: `{manifest.get('project_name')}`")
    lines.append("")
    lines.append("## Outputs")
    for key in ["master_input", "target_cued", "override_cued", "control_phase_scrambled", "cue_schedule_json", "cue_schedule_csv"]:
        val = manifest.get("outputs", {}).get(key)
        if val:
            lines.append(f"- **{key}:** `{val}`")
    lines.append("")
    lines.append("## SHA-256")
    for key, val in manifest.get("sha256", {}).items():
        lines.append(f"- **{key}:** `{val}`")
    lines.append("")
    lines.append("## Cue Design")
    cue = manifest.get("cue_design", {})
    for k, v in cue.items():
        lines.append(f"- **{k}:** `{v}`")
    lines.append("")
    lines.append("## Critical method rule")
    lines.append("")
    lines.append("Target and Contextual Override are generated from the same cue-embedded video. Only the participant instructions should differ. The phase-scrambled control is generated from that cue-embedded target so cue timing and low-level cue energy are represented in the control branch as well.")
    lines.append("")
    lines.append("## Boundary")
    lines.append("")
    lines.append("This tool prepares media. It does not certify meaning, empathy, neural endpoints, or task compliance. The output should be followed by StimulusFingerprint QC, protocol acquisition, and the Master Comprehensive PR-AYC-G analysis suite.")
    (out_dir / "PRAYCG_MediaPrep_v1_6M_report.md").write_text("\n".join(lines), encoding="utf-8")


def run_media_prep(args: argparse.Namespace, progress_cb=None) -> Path:
    master = Path(args.master).expanduser().resolve()
    if not master.exists():
        raise FileNotFoundError(master)
    project = sanitize_name(args.project_name or master.stem)
    out_root = Path(args.out_root).expanduser().resolve()
    stamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = out_root / f"{project}_MediaPrep_v1_6M_{stamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    if progress_cb:
        progress_cb(f"Output folder: {out_dir}")

    props = get_video_props(master)
    events = make_cue_schedule(
        duration_sec=float(props["duration_sec"] if args.max_seconds in (None, 0) else min(props["duration_sec"], args.max_seconds)),
        seed=int(args.seed),
        interval_sec=float(args.cue_interval),
        display_duration_sec=float(args.cue_duration),
        start_delay_sec=float(args.start_delay),
        min_value=int(args.min_value),
        max_value=int(args.max_value),
        position=args.position,
    )

    target_cued = out_dir / f"stimulus_target_cued_{project}_v1_6M.mp4"
    override_cued = out_dir / f"stimulus_override_cued_{project}_v1_6M.mp4"
    control = out_dir / f"stimulus_control_cued_phase_scrambled_{project}_v1_6M.mp4"
    schedule_json = out_dir / f"cue_schedule_{project}_v1_6M.json"
    schedule_csv = out_dir / f"cue_schedule_{project}_v1_6M.csv"

    if progress_cb:
        progress_cb("Rendering cue-embedded Target video...")
    cue_render_summary = render_cued_video(
        master,
        target_cued,
        events,
        position=args.position,
        badge_alpha=float(args.badge_alpha),
        font_scale_factor=float(args.font_scale_factor),
        overwrite=bool(args.overwrite),
        progress_cb=progress_cb,
        max_seconds=args.max_seconds,
    )

    if progress_cb:
        progress_cb("Copying cue-embedded Target to cue-embedded Contextual Override...")
    shutil.copy2(target_cued, override_cued)

    metadata = {
        "schema": "PRAYCG_number_cue_schedule_v1_6M",
        "created_utc": now_utc_iso(),
        "input_video": str(master),
        "input_sha256": sha256_file(master),
        "output_cued_video": str(target_cued),
        "output_cued_sha256": sha256_file(target_cued),
        "output_override_video": str(override_cued),
        "output_override_sha256": sha256_file(override_cued),
        "video": props,
        "cue_design": {
            "seed": int(args.seed),
            "interval_sec": float(args.cue_interval),
            "display_duration_sec": float(args.cue_duration),
            "start_delay_sec": float(args.start_delay),
            "min_value": int(args.min_value),
            "max_value": int(args.max_value),
            "position": args.position,
            "alpha": float(args.badge_alpha),
            "font_scale_factor": float(args.font_scale_factor),
            "contrast_protected_badge": True,
            "fixed_position_reason": "Fixed safe-zone placement reduces visual-search/saccade confounds relative to moving numbers.",
            "recommended_use": "Use the same cue-embedded stimulus for Target and Contextual Override. Only instructions should differ.",
            "control_generation": "Phase-scramble the cue-embedded Target to generate the Control.",
        },
        "audio_muxed_from_original": True,
    }
    write_schedule_files(events, schedule_json, schedule_csv, metadata)

    scramble_summary = None
    if args.make_control:
        if progress_cb:
            progress_cb("Generating phase-scrambled Control from cue-embedded Target...")
        scramble_summary = phase_scramble_media(
            target_cued,
            control,
            seed=int(args.seed) + 31337,
            contrast_strength=float(args.scramble_contrast_strength),
            overwrite=bool(args.overwrite),
            progress_cb=progress_cb,
            max_seconds=args.max_seconds,
        )

    sha = {
        "master_input": sha256_file(master),
        "target_cued": sha256_file(target_cued),
        "override_cued": sha256_file(override_cued),
    }
    if control.exists():
        sha["control_phase_scrambled"] = sha256_file(control)

    manifest = {
        "schema": SCHEMA,
        "created_utc": now_utc_iso(),
        "project_name": project,
        "outputs": {
            "output_dir": str(out_dir),
            "master_input": str(master),
            "target_cued": str(target_cued),
            "override_cued": str(override_cued),
            "control_phase_scrambled": str(control) if control.exists() else None,
            "cue_schedule_json": str(schedule_json),
            "cue_schedule_csv": str(schedule_csv),
        },
        "sha256": sha,
        "video_props": props,
        "cue_design": metadata["cue_design"],
        "cue_count": len(events),
        "expected_sum": int(sum(ev.value for ev in events)),
        "cue_render_summary": cue_render_summary,
        "scramble_summary": scramble_summary,
        "boundary": "Media prep only. Requires StimulusFingerprint QC and physiology analysis before empirical claims.",
    }
    (out_dir / "media_prep_manifest_v1_6M.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    make_report(out_dir, manifest)

    # Optional fingerprint run, if bundled beside this script.
    if args.run_fingerprint:
        script_path = Path(__file__).resolve().parents[1] / "stimulus_fingerprint_v1_5" / "scripts" / "praycg_stimulus_fingerprint_batch_ui_v1_5.py"
        if not script_path.exists():
            # Also check package root sibling.
            script_path = Path(__file__).resolve().parents[1] / ".." / "stimulus_fingerprint_v1_5" / "scripts" / "praycg_stimulus_fingerprint_batch_ui_v1_5.py"
        if script_path.exists() and control.exists():
            if progress_cb:
                progress_cb("Running StimulusFingerprint v1.5 on generated suite...")
            fp_out = out_dir / "StimulusFingerprint_v1_5"
            cmd = [
                sys.executable, str(script_path), "--no-gui",
                "--project-name", project,
                "--control", str(control),
                "--target", str(target_cued),
                "--override", str(override_cued),
                "--cue-schedule-json", str(schedule_json),
                "--cue-schedule-csv", str(schedule_csv),
                "--out-root", str(fp_out),
                "--sample-fps", str(args.fingerprint_sample_fps),
                "--resize-width", str(args.fingerprint_resize_width),
            ]
            subprocess.run(cmd, check=True)
        else:
            if progress_cb:
                progress_cb("StimulusFingerprint v1.5 script not found or control missing; skipped fingerprint step.")

    if progress_cb:
        progress_cb(f"DONE. Expected sum = {sum(ev.value for ev in events)}. Output = {out_dir}")
    return out_dir


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="PRAYCG MediaPrep GUI v1.6M")
    p.add_argument("--no-gui", action="store_true", help="Run from command line without GUI.")
    p.add_argument("--master", default="", help="Master source MP4.")
    p.add_argument("--out-root", default="outputs", help="Output root folder.")
    p.add_argument("--project-name", default="", help="Project/stimulus suite name.")
    p.add_argument("--seed", type=int, default=DEFAULT_SEED)
    p.add_argument("--start-delay", type=float, default=3.0)
    p.add_argument("--cue-interval", type=float, default=3.0)
    p.add_argument("--cue-duration", type=float, default=0.85)
    p.add_argument("--min-value", type=int, default=1)
    p.add_argument("--max-value", type=int, default=10)
    p.add_argument("--position", default="upper_right", choices=["upper_right", "upper_left", "lower_right", "lower_left"])
    p.add_argument("--badge-alpha", type=float, default=0.78)
    p.add_argument("--font-scale-factor", type=float, default=0.95)
    p.add_argument("--scramble-contrast-strength", type=float, default=0.65)
    p.add_argument("--make-control", action="store_true", default=True)
    p.add_argument("--no-control", action="store_false", dest="make_control")
    p.add_argument("--run-fingerprint", action="store_true", help="Run bundled StimulusFingerprint v1.5 after media generation.")
    p.add_argument("--fingerprint-sample-fps", type=float, default=5.0)
    p.add_argument("--fingerprint-resize-width", type=int, default=320)
    p.add_argument("--max-seconds", type=float, default=None, help="Optional quick-test limit in seconds. Omit for full video.")
    p.add_argument("--overwrite", action="store_true")
    return p


def launch_gui(defaults: argparse.Namespace) -> None:
    import tkinter as tk
    from tkinter import filedialog, messagebox

    root = tk.Tk()
    root.title("PRAYCG MediaPrep Suite v1.6M")
    root.geometry("820x720")

    vars: Dict[str, tk.StringVar] = {}
    bools: Dict[str, tk.BooleanVar] = {}

    def add_row(label: str, key: str, default: str, browse: Optional[str] = None, row: int = 0):
        tk.Label(root, text=label, anchor="w").grid(row=row, column=0, sticky="w", padx=10, pady=4)
        vars[key] = tk.StringVar(value=default)
        ent = tk.Entry(root, textvariable=vars[key], width=72)
        ent.grid(row=row, column=1, sticky="we", padx=5, pady=4)
        if browse == "file":
            def _browse_file(k=key):
                path = filedialog.askopenfilename(title="Select MP4", filetypes=[("MP4 files", "*.mp4"), ("All files", "*.*")])
                if path:
                    vars[k].set(path)
                    if k == "master" and not vars["project_name"].get().strip():
                        vars["project_name"].set(sanitize_name(Path(path).stem))
            tk.Button(root, text="Browse", command=_browse_file).grid(row=row, column=2, padx=5, pady=4)
        elif browse == "dir":
            def _browse_dir(k=key):
                path = filedialog.askdirectory(title="Select output folder")
                if path:
                    vars[k].set(path)
            tk.Button(root, text="Browse", command=_browse_dir).grid(row=row, column=2, padx=5, pady=4)

    r = 0
    add_row("Master MP4", "master", "", browse="file", row=r); r += 1
    add_row("Output root", "out_root", str(Path.cwd() / "outputs"), browse="dir", row=r); r += 1
    add_row("Project name", "project_name", "", row=r); r += 1
    add_row("Seed", "seed", str(DEFAULT_SEED), row=r); r += 1
    add_row("Cue start delay seconds", "start_delay", "3.0", row=r); r += 1
    add_row("Cue interval seconds", "cue_interval", "3.0", row=r); r += 1
    add_row("Cue display duration seconds", "cue_duration", "0.85", row=r); r += 1
    add_row("Minimum cue value", "min_value", "1", row=r); r += 1
    add_row("Maximum cue value", "max_value", "10", row=r); r += 1
    add_row("Cue position", "position", "upper_right", row=r); r += 1
    add_row("Badge opacity alpha", "badge_alpha", "0.78", row=r); r += 1
    add_row("Font scale factor", "font_scale_factor", "0.95", row=r); r += 1
    add_row("Control scramble contrast strength", "scramble_contrast_strength", "0.65", row=r); r += 1
    add_row("Quick-test max seconds (blank = full video)", "max_seconds", "", row=r); r += 1
    add_row("Fingerprint sample FPS", "fingerprint_sample_fps", "5", row=r); r += 1
    add_row("Fingerprint resize width", "fingerprint_resize_width", "320", row=r); r += 1

    bools["overwrite"] = tk.BooleanVar(value=True)
    bools["run_fingerprint"] = tk.BooleanVar(value=False)
    bools["make_control"] = tk.BooleanVar(value=True)
    tk.Checkbutton(root, text="Overwrite outputs inside the new output folder if needed", variable=bools["overwrite"]).grid(row=r, column=1, sticky="w", padx=5, pady=4); r += 1
    tk.Checkbutton(root, text="Generate phase-scrambled Control from cue-embedded Target", variable=bools["make_control"]).grid(row=r, column=1, sticky="w", padx=5, pady=4); r += 1
    tk.Checkbutton(root, text="Run StimulusFingerprint v1.5 after media generation", variable=bools["run_fingerprint"]).grid(row=r, column=1, sticky="w", padx=5, pady=4); r += 1

    log = tk.Text(root, height=14, width=100)
    log.grid(row=r, column=0, columnspan=3, sticky="nsew", padx=10, pady=10); r += 1
    root.grid_columnconfigure(1, weight=1)
    root.grid_rowconfigure(r-1, weight=1)

    def progress(msg: str):
        def _append():
            log.insert("end", msg + "\n")
            log.see("end")
        root.after(0, _append)

    def build_args_from_gui() -> argparse.Namespace:
        ns = build_arg_parser().parse_args([])
        ns.no_gui = False
        ns.master = vars["master"].get().strip()
        ns.out_root = vars["out_root"].get().strip()
        ns.project_name = vars["project_name"].get().strip()
        ns.seed = int(vars["seed"].get().strip())
        ns.start_delay = float(vars["start_delay"].get().strip())
        ns.cue_interval = float(vars["cue_interval"].get().strip())
        ns.cue_duration = float(vars["cue_duration"].get().strip())
        ns.min_value = int(vars["min_value"].get().strip())
        ns.max_value = int(vars["max_value"].get().strip())
        ns.position = vars["position"].get().strip()
        ns.badge_alpha = float(vars["badge_alpha"].get().strip())
        ns.font_scale_factor = float(vars["font_scale_factor"].get().strip())
        ns.scramble_contrast_strength = float(vars["scramble_contrast_strength"].get().strip())
        ns.overwrite = bool(bools["overwrite"].get())
        ns.run_fingerprint = bool(bools["run_fingerprint"].get())
        ns.make_control = bool(bools["make_control"].get())
        ns.fingerprint_sample_fps = float(vars["fingerprint_sample_fps"].get().strip())
        ns.fingerprint_resize_width = int(vars["fingerprint_resize_width"].get().strip())
        ms = vars["max_seconds"].get().strip()
        ns.max_seconds = float(ms) if ms else None
        return ns

    def run_thread():
        try:
            ns = build_args_from_gui()
            if not ns.master:
                raise ValueError("Select a Master MP4 first.")
            out = run_media_prep(ns, progress_cb=progress)
            root.after(0, lambda: messagebox.showinfo("PRAYCG MediaPrep complete", f"Media prep complete.\n\nOutput folder:\n{out}"))
        except Exception as exc:
            tb = traceback.format_exc()
            progress(tb)
            root.after(0, lambda: messagebox.showerror("PRAYCG MediaPrep error", str(exc)))

    def on_run():
        log.delete("1.0", "end")
        progress("Starting PRAYCG MediaPrep Suite v1.6M...")
        t = threading.Thread(target=run_thread, daemon=True)
        t.start()

    tk.Button(root, text="Run Full MediaPrep Suite", command=on_run, bg="#ddeeff", height=2).grid(row=r, column=1, sticky="we", padx=5, pady=10)
    tk.Label(root, text="Workflow: one master MP4 -> cued Target + identical cued Override + phase-scrambled Control + cue schedule.", anchor="w").grid(row=r+1, column=0, columnspan=3, sticky="w", padx=10)
    root.mainloop()


def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()
    if args.no_gui:
        if not args.master:
            parser.error("--master is required with --no-gui")
        run_media_prep(args, progress_cb=lambda m: print(m, flush=True))
    else:
        launch_gui(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
